import { Component, OnInit } from '@angular/core';
import { TranslateService } from '@ngx-translate/core'; // 1
import { LogicService } from '../../app/services/logic.service'
import { IData } from '../../app/services/logic.service'
import { Observable } from "rxjs";
import{PopoverPage} from '../popover/popover.page'
import { PopoverController } from '@ionic/angular';
import { ModalController } from '@ionic/angular';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-tab1',
  templateUrl: './tab1.page.html',
  styleUrls: ['./tab1.page.scss'],
})



export class Tab1Page implements OnInit {

 

  idiomaSeleccionado:any;

  // ../assets/i18n/en1.json

  ngOnInit() {
    this.idiomaSeleccionado = this.route.snapshot.paramMap.get('id');
    
    switch(this.idiomaSeleccionado) { 
      case 'en': { 
        this.array= this.arrayINGLES;
       break; 
      } 
      case 'rus': { 
         this.array= this.arrayRusia;
         break; 
      } 
      case 'por': { 
        this.array= this.arrayPor;
        break; 
     } 
     case'fr':{
       this.array=this.arrayFra;
       break
     }
     case'esp':{
      this.array=this.arrayEs;
      break
    }

    case'de':{
      this.array=this.arrayDe;
      break
    }
     
     
      
      default: { 
        this.array= this.arrayINGLES;
         break; 
      } 
   } 

 
  }
  constructor(public modalController: ModalController,public popoverController: PopoverController,private route: ActivatedRoute) { 

  

  }
  
  
  popup() {
this.modalController.create({component:PopoverPage}).then((modalElement)=>{
  modalElement.present();
})
  }

  public array:any[];

  public arrayDe:any=[ {
      "login_titulo_login":"ANMELDUNG",
      "login_Textoformulario_email":"EMAIL",
      "login_Textoformulario":"Passwort",
      "login_PlaceHolder_Ingrese_email":"Email eingeben",
      "login_PlaceHolder_Ingrese_clave":"Enter-Taste",
      "login_link_CrearUnaNuevaCuenta":"Ein neues Konto erstellen",
      "login_link_olvidaste_tu_clave": "Passwort vergessen?",
      "login_btn_Ingresar": "REINKOMMEN",
      "login_btn_ElegirUsuario": "BENUTZER AUSWÄHLEN",
      "login_Mensaje_IngresarMailvalido":"Bitte geben Sie eine gültige Email-Adresse ein",
      "login_Mensaje_claveMas6Caracteres":"Ihr Passwort muss mehr als 6 Zeichen enthalten",
      "________________________________":"",
      "tipo-registro_titulo_tiporegistro":"Aufnahmetyp",
      "tipo-registro_btn_clienteRegistrado":"Registrierter Kunde",
      "tipo_Registro_btn_clienteAnonimo":"Anonymer Kunde",
      "_____________________________":"",
      "Alta-Cliente_Titulo":"Client laden",
      "Alta-Cliente_Formulario_Texto_Nombre":"Name",
      "Alta-Cliente_Formulario_Texto_Apellido":"Nachname",
      "Alta-Cliente_Formulario_Texto_DNI":"DNI",
      "Alta-Cliente_Formulario_Texto_Correo":"Correo",
      "Alta-Cliente_Formulario_Texto_Clave":"Passwort",
      "Alta-Cliente_Formulario_PlaceHolder_Nombre":"Name",
      "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Nachname",
      "Alta-Cliente_Formulario_PlaceHolder_DNI":"Geben Sie DNI ein",
      "Alta-Cliente_Formulario_PlaceHolder_Correo":"Mail eingeben",
      "Alta-Cliente_Formulario_PlaceHolder_Clave":"Passwort eingeben",
      "Alta-Cliente_btn_Scannear_DNI":"DNI scannen",
      "Alta-Cliente_btn_Guardar":"sparen",
      "______________________________":"",
      "alta-duenio_Titulo":"Laden Sie den Eigentümer / Supervisor hoch",
      "alta-duenio_Formulario_Nombre":"Name",
      "alta-duenio_Formulario_Apellido":"Nachname",
      "alta-duenio_Formulario_Cuil":"CUIL",
      "alta-duenio_Formulario_Correo":"Mail",
      "alta-duenio_Formulario_TipoDeEmpleado":"Art des Mitarbeiters",
      "alta-duenio_Formulario_Select_OptionSupervisor":"derOberaufseher",
      "alta-duenio_Formulario_Select_OptionDuenio":"Inhaber",
      "alta-duenio_Formulario_BTN_ScannerDNI":"Dokumente scannen",
      "alta-duenio_Formulario_BTN_Guardar":"sparen",
      "alta-duenio_Listado_Perfil":"Profil",
      "alta-duenio_Listado_DNI":"DNI",
      "________________Altaempleado_____________________":"",
      "alta-empleado_Titulo":"Mitarbeiter hinzufügen",
      "alta-empleado_Formulario_Nombre":"Name",
      "alta-empleado_Formulario_Apellido":"Nachname",
      "alta-empleado_Formulario_Cuil":"CUIL",
      "alta-empleado_Formulario_Correo":"Mail",
      "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Geben Sie DNI ein",
      "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Geben Sie CUIL ein",
      "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Mail eingeben",
      "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Mitarbeitertyp",
      "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Wählen Sie den Mitarbeitertyp aus",
      "alta-empleado_Formulario_BTN_ScannerDNI":"ID scannen",
      "alta-empleado_Formulario_BTN_Guardar":"sparen",
      "Alta-empleado_Formulario_Option_Cocinero":"Koch",
      "Alta-empleado_Formulario_Option_Bartender":"Barmann",
      "Alta-empleado_Formulario_Option_Mozo":"Bedienung",
      "Alta-empleado_ListadoFormulario_Perfil":"Profil",
      "Alta-empleado_ListadoFormulario_Empleado":"Mitarbeiter",
  
      "_______________________________":"",
      "alta-anonimo_titulo":"Laden Sie einen anonymen Client hoch",
      "alta-anonimo_TextoFormulario_nombre":"Name",
      "alta-anonimo_TextoFormularioCorreo":"Mail",
      "alta-anonimo_PlaceHolderNombre":"Name eingeben",
      "alta-anonimo_PlaceHolderCorreo":"Mail eingeben",
      "alta-anonimo_PlaceHolderIngreseClave":"Passwort eingeben",
      "__________________________________":"",
      "alta-mesa_titulo":"Tabelle laden",
      "alta-mesa_TextoFormulario_codigo_de_mesa":"Tabellencode",
      "alta-mesa_TextoFormulario_cantidad_de_personas":"Anzahl von Leuten",
      "alta-mesa_TextoFormulario_tipo_de_mesa":"Tabellentyp",
      "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Wählen Sie den Tabellentyp",
      "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Wählen Sie die Anzahl der Personen",
      "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Geben Sie den Tabellencode ein",
      "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
      "alta-mesa_TextoFormulario_select_Option_Fumadores":"Raucher",
      "alta-mesa_TextoFormulario_select_Option_Discapacitados":"Behindert",
      "alta-mesa_TextoFormulario_select_Option_Normal":"Normal",
      "alta-mesa_btn_Cancelar":"Stornieren",
      "alta-mesa_btn_Aceptar":"Akzeptieren",
      "alta-mesa_Listado_Estado":"Zustand",
  
  
  
      "___________________________________":"",
  
      "home_btn_CreatuPedido": "ERSTELLEN SIE IHRE BESTELLUNG",
      "home_btn_ListadoComida":"LEBENSMITTELLISTE",
      "home_btn_ReservaCliente":"KUNDENRESERVIERUNG",
      "home_btn_CargarMesa":"CARGAR MESA",
      "home_btn_ConfirmarLLegadaPedido":"BESTÄTIGEN SIE DIE ANKUNFT IHRER BESTELLUNG",
      "home_btn_EscanearCodigo":"Scannen Sie Ihren Code",
      "home_btn_AltaEmpeado":"ENTLADUNG DES MITARBEITERS",
      "home_btn_CargarCliente":"KUNDE LADEN",
      "home_btn_ListadoCliente":"KUNDENLISTE",
      "home_btn_AbrirMesa": "OFFENER TISCH",
      "home_btn_cerrarMesa": "TABELLE SCHLIESSEN",
      "home_btn_TomarPedido":"BESTELLEN",
      "home_btn_TomarPedidoCocina":"BESTELLKÜCHE",
      "home_btn_ListadoIngreso":"EINKOMMENSLISTE",
      "home_btn_HabilitarReservas":"RESERVIERUNGEN AKTIVIEREN",
      "home_btn_Hacetudelivery":"Machen Sie Ihre Lieferung!",
      "home_btn_Habilitar_Pedido_Delivery":"LIEFERBESTELLUNG AKTIVIERENY",
      "home_btn_enviar_Pedido":"SENDEN SIE DIE BESTELLUNG",
      "home_btn_chat":"PLAUDERN",
      "home_btn_encuesta_empleado":"MITARBEITERBEFRAGUNG",
      "home_btn_Cargar_Ciente":"KUNDE LADEN",
      "home_btn_tomar_pedido_bar":"BESTELLEN SIE BAR",
      "__________________________":"",
      "comida-list_titulo":"BESTELLEN SIE BAR",
      "comida-list_subtitulo":"LEBENSMITTELBUCHSTABEN",
      "comida-list_bebidas":"GETRÄNKBUCHSTABEN",
      "comida-list_postre":"DESSERT BRIEFE ",
  
      "comida-list_Precio":"Preis",
      "________________________":"",
      "comida-detail_Titulo":"Beschreibung",
      "comida-detail_Descripcion":"Beschreibung",
      "comida-detail_Precio":"Preis",
      "comida-detail_Tiempo":"Tiempo",
      "________________":"",
      "comida-create_Titulo":"Laden Sie Lebensmittel",
      "comida-create_FormularioTextNombre":"Name",
      "comida-create_FormularioTextCodigo":"Code",
      "comida-create_FormularioTextDescripcion":"Beschreibung",
      "comida-create_FormularioTextPrecio":"Preis",
      "comida-create_FormularioTextPreparacion":"Vorbereitung",
      "comida-create_FormularioTextTipoDeProducto":"Art des Produkts",
      "comida-create_PlaceHolder_NombreDeComida":"Name des Lebensmittels",
      "comida-create_PlaceHolder_Codigo":"Lebensmittelcode",
      "comida-create_PlaceHolder_Descripcion":"Was ist es?",
      "comida-create_PlaceHolder_CuantoCuesta":"Wie viel?",
      "comida-create_PlaceHolder_CuantoTardaenHacerce":"Wie lange dauert es?",
      "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Art auswählen",
      "comida-create_Select_PlaceHolder_Comida":"Essen",
      "comida-create_Select_PlaceHolder_Bebida":"Getränk",
      "comida-create_Select_PlaceHolder_Postre":"Dessert",
      "comida-create_Select_Boton_Cancelar":"Stornieren",
      "comida-create_Select_Boton_Aceptar":"Akzeptieren",
      "_______________________":"",
      "listado-cliente_Titulo":"Klienten Liste",
      "listado-cliente_formulario":"Profil",
      "_____________________________________":"",
      "abrir-mesa_titulo":"Offener Tisch",
      "abrir-mesa_btn_limpiarDatos":"Daten löschens",
      "abrir-mesa_select_option_estado":"Zustand",
      "abrir-mesa_select_option_cliente":"Klient",
      "abrir-mesa_select_option_ocupado":"belegt",
      "abrir-mesa_select_option_disponible":"verfügbar",
      "abrir-mesa_select_option_reservada":"reserviert",
      "abrir-mesa_btn_cancelar":"stornieren",
      "abrir-mesa_btn_aceptar":"akzeptieren",
      "___________________________________________":"",
      "tomarpedidos_titulo":"Bestellung hochladen",
      "tomarpedidos_listosParaEntregar":"Bestellung hochladen",
      "tomarpedidos_pendientes_de_aprobacion":"Bestellungen bis zur Genehmigung",
      "______________________________________--_____":"",
      "ingreso_Titulo ":"Warteliste",
      "ingreso-cliente_en_espera":"wartender Kunde",
      "ingreso-estado":"Zustand",
      "ingreso-btn-confirmarIngreso":"Login bestätigen",
      "ingreso-btn-DenegarAcceso":"Zugriff verweigern",
      "______________________________________--__________":"",
      "Habilitar-Reservas_Titulo ":"Reservierungen aktivieren",
      "Habilitar-Reservas_Fecha ":"Datum",
      "Habilitar-Reservas_Hora ":"Stunde",
      "Habilitar-Reservas_Usuario ":"Benutzer",
      "Habilitar-Reservas_Cantidad_de_Personas ":"Anzahl von Leuten",
      "Habilitar-Reservas_Mesa ":"Tabelle",
      "Habilitar-Btn-Habilitar ":"Aktivieren",
      "Habilitar-Btn-Rechazar ":"Ablehnen",
      "Habilitar-option-Cancelar ":"Stornieren",
      "Habilitar-option-Aceptar":"Akzeptieren"
  
  
   }
  ];


  public arrayEs:any = [{
    "login_titulo_login":"INICIAR SESIÓN",
    "login_Textoformulario_email":"CORREO ELECTRONICO",
    "login_Textoformulario":"CLAVE",
    "login_PlaceHolder_Ingrese_email":"Ingrese email",
    "login_PlaceHolder_Ingrese_clave":"Ingrese clave",
    "login_link_CrearUnaNuevaCuenta":"Crear una Nueva Cuenta",
    "login_link_olvidaste_tu_clave": "Olvidaste tu clave?",
    "login_btn_Ingresar": "INGRESAR",
    "login_btn_ElegirUsuario": "ELEGIR USUARIO",
    "login_Mensaje_IngresarMailvalido":"Por favor ingrese un email valido",
    "login_Mensaje_claveMas6Caracteres":"Su clave debe poseer mas de 6 caracteres",

    "________________________________":"",
    "tipo-registro_titulo_tiporegistro":"Tipo Registro",
    "tipo-registro_btn_clienteRegistrado":"Cliente Registrado",
    "tipo_Registro_btn_clienteAnonimo":"Cliente Anonimo",
    "_____________________________":"",
    "Alta-Cliente_Titulo":"Cargar Cliente",
    "Alta-Cliente_Formulario_Texto_Nombre":"Nombre",
    "Alta-Cliente_Formulario_Texto_Apellido":"Apellido",
    "Alta-Cliente_Formulario_Texto_DNI":"DNI",
    "Alta-Cliente_Formulario_Texto_Correo":"Correo",
    "Alta-Cliente_Formulario_Texto_Clave":"Clave",
    "Alta-Cliente_Formulario_PlaceHolder_Nombre":"Nombre",
    "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Ingresar Apellido",
    "Alta-Cliente_Formulario_PlaceHolder_DNI":"Ingresar DNI",
    "Alta-Cliente_Formulario_PlaceHolder_Correo":"Ingresar Correo",
    "Alta-Cliente_Formulario_PlaceHolder_Clave":"Ingreser Clave",
    "Alta-Cliente_btn_Scannear_DNI":"Scannear DNI",
    "Alta-Cliente_btn_Guardar":"Guardar",
    "______________________________":"",
    "alta-duenio_Titulo":"Cargar Dueño/ Supervisor",
    "alta-duenio_Formulario_Nombre":"Nombre",
    "alta-duenio_Formulario_Apellido":"Apellido",
    "alta-duenio_Formulario_Cuil":"CUIL",
    "alta-duenio_Formulario_Correo":"Correo",
    "alta-duenio_Formulario_TipoDeEmpleado":"Tipo de Empleado",
    "alta-duenio_Formulario_Select_OptionSupervisor":"Supervisor",
    "alta-duenio_Formulario_Select_OptionDuenio":"Dueño",
    "alta-duenio_Formulario_BTN_ScannerDNI":"Scannear",
    "alta-duenio_Formulario_BTN_Guardar":"Guardar",
    "alta-duenio_Listado_Perfil":"Perfil",
    "alta-duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta-empleado_Titulo":"Agregar Empleado",
    "alta-empleado_Formulario_Nombre":"Nombre",
    "alta-empleado_Formulario_Apellido":"Apellido",
    "alta-empleado_Formulario_Cuil":"CUIL",
    "alta-empleado_Formulario_Correo":"Correo",
    "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Ingreser DNI",
    "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Ingreser CUIL",
    "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Ingresar Correo",
    "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Tipo de Empleado",
    "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Seleccione tipo de empleados",
    "alta-empleado_Formulario_BTN_ScannerDNI":"Scannear DNI",
    "alta-empleado_Formulario_BTN_Guardar":"Guardar",
    "Alta-empleado_Formulario_Option_Cocinero":"Cocinero",
    "Alta-empleado_Formulario_Option_Bartender":"Bartender",
    "Alta-empleado_Formulario_Option_Mozo":"Mozo",
    "Alta-empleado_ListadoFormulario_Perfil":"Perfil",
    "Alta-empleado_ListadoFormulario_Empleado":"Empleado",

    "_______________________________":"",
    "alta-anonimo_titulo":"Cargar Cliente Anonimo",
    "alta-anonimo_TextoFormulario_nombre":"Nombre",
    "alta-anonimo_TextoFormularioCorreo":"Correo",
    "alta-anonimo_PlaceHolderNombre":"Ingrese Nombre",
    "alta-anonimo_PlaceHolderCorreo":"Ingrese Correo",
    "alta-anonimo_PlaceHolderIngreseClave":"Ingrese Clave",
    "__________________________________":"",
    "alta-mesa_titulo":"Cargar Mesa",
    "alta-mesa_TextoFormulario_codigo_de_mesa":"Codigo de Mesa",
    "alta-mesa_TextoFormulario_cantidad_de_personas":"Cantidad de Personas",
    "alta-mesa_TextoFormulario_tipo_de_mesa":"Tipo de Mesa",
    "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Seleccionar tipo de mesa",
    "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Seleccionar cantidad de personas",
    "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Ingrese codigo de mesa",
    "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta-mesa_TextoFormulario_select_Option_Fumadores":"Fumadores",
    "alta-mesa_TextoFormulario_select_Option_Discapacitados":"Discapacitados",
    "alta-mesa_TextoFormulario_select_Option_Normal":"Normal",
    "alta-mesa_btn_Cancelar":"Cancelar",
    "alta-mesa_btn_Aceptar":"Aceptar",
    "alta-mesa_Listado_Estado":"Estado",



    "___________________________________":"",

    "home_btn_CreatuPedido": "CREA TU PEDIDO",
    "home_btn_ListadoComida":"LISTADO DE COMIDAS",
    "home_btn_ReservaCliente":"RESERVA CLIENTE",
    "home_btn_CargarMesa":"CARGAR MESA",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRMANOS LA LLEGADA DE TU PEDIDO",
    "home_btn_EscanearCodigo":"ESCANEAR TU CODIGO",
    "home_btn_AltaEmpeado":"ALTA DE EMPLEADO",
    "home_btn_CargarCliente":"CARGAR CLIENTE",
    "home_btn_ListadoCliente":"LISTADO DE CLIENTE",
    "home_btn_AbrirMesa": "ABRIR MESA",
    "home_btn_cerrarMesa": "CERRAR MESA",
    "home_btn_TomarPedido":"TOMAR PEDIDO",
    "home_btn_TomarPedidoCocina":"TOMAR PEDIDO COCINA",
    "home_btn_ListadoIngreso":"LISTADO DE INGRESO",
    "home_btn_HabilitarReservas":"HABILITAR RESEVAS",
    "home_btn_Hacetudelivery":"HACE TU DELIVERY!",
    "home_btn_Habilitar_Pedido_Delivery":"HABILITAR PEDIDO DELIVERY",
    "home_btn_enviar_Pedido":"ENVIAR PEDIDO",
    "home_btn_chat":"CHAT",
    "home_btn_encuesta_empleado":"ENCUESTA EMPLEADO",
    "home_btn_Cargar_Ciente":"CARGAR CLIENTE",
    "home_btn_tomar_pedido_bar":"TOMAR PEDIDOS BAR",
    "__________________________":"",
    "comida-list_titulo":"TOMAR PEDIDOS BAR",
    "comida-list_subtitulo":"CARTAS DE COMIDA",
    "comida-list_bebidas":"CARTAS DE BEBIDAS",
    "comida-list_postre":"CARTAS DE POSTRE",

    "comida-list_Precio":"Precio",
    "________________________":"",
    "comida-detail_Titulo":"Descripción",
    "comida-detail_Descripcion":"Descripción",
    "comida-detail_Precio":"Precio",
    "comida-detail_Tiempo":"Tiempo",
    "________________":"",
    "comida-create_Titulo":"Cargar Comida",
    "comida-create_FormularioTextNombre":"Nombre",
    "comida-create_FormularioTextCodigo":"Codigo",
    "comida-create_FormularioTextDescripcion":"Descripción",
    "comida-create_FormularioTextPrecio":"Precio",
    "comida-create_FormularioTextPreparacion":"Preparacion",
    "comida-create_FormularioTextTipoDeProducto":"Tipo de Producto",
    "comida-create_PlaceHolder_NombreDeComida":"Nombre de comida",
    "comida-create_PlaceHolder_Codigo":"Codigo de comida",
    "comida-create_PlaceHolder_Descripcion":"Que es?",
    "comida-create_PlaceHolder_CuantoCuesta":"Cuanto Cuesta?",
    "comida-create_PlaceHolder_CuantoTardaenHacerce":"Cuanto Tarda en Hacerse?",
    "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Seleccione El tipo",
    "comida-create_Select_PlaceHolder_Comida":"Comida",
    "comida-create_Select_PlaceHolder_Bebida":"Bebida",
    "comida-create_Select_PlaceHolder_Postre":"Postre",
    "comida-create_Select_Boton_Cancelar":"Cancelar",
    "comida-create_Select_Boton_Aceptar":"Aceptar",
    "_______________________":"",
    "listado-cliente_Titulo":"Listado CLiente",
    "listado-cliente_formulario":"Perfil",
    "_____________________________________":"",
    "abrir-mesa_titulo":"Abrir Mesa",
    "abrir-mesa_btn_limpiarDatos":"Limpiar Datos",
    "abrir-mesa_select_option_estado":"estado",
    "abrir-mesa_select_option_cliente":"cliente",
    "abrir-mesa_select_option_ocupado":"ocupado",
    "abrir-mesa_select_option_disponible":"disponible",
    "abrir-mesa_select_option_reservada":"reservada",
    "abrir-mesa_btn_cancelar":"cancelar",
    "abrir-mesa_btn_aceptar":"aceptar",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Cargar Pedido",
    "tomarpedidos_listosParaEntregar":"Listo Para entregar",
    "tomarpedidos_pendientes_de_aprobacion":"Pedidos Pendientes de Aprobacion",
    "______________________________________--_____":"",
    "ingreso_Titulo ":"Lista de Espera",
    "ingreso-cliente_en_espera":"cliente en espera",
    "ingreso-estado":"estado",
    "ingreso-btn-confirmarIngreso":"Confirmar Ingreso",
    "ingreso-btn-DenegarAcceso":"Denegar Acceso",
    "______________________________________--__________":"",
    "Habilitar-Reservas_Titulo ":"Habilitar Reservas",
    "Habilitar-Reservas_Fecha ":"Fecha",
    "Habilitar-Reservas_Hora ":"Hora",
    "Habilitar-Reservas_Usuario ":"Usuario",
    "Habilitar-Reservas_Cantidad_de_Personas ":"Cantidad de Personas",
    "Habilitar-Reservas_Mesa ":"Mesa",
    "Habilitar-Btn-Habilitar ":"Habilitar",
    "Habilitar-Btn-Rechazar ":"Rechazar",
    "Habilitar-option-Cancelar ":"Cancelar",
    "Habilitar-option-Aceptar":"Aceptar"


 }];

  public arrayFra:any= [{
    "login_titulo_login":"CONNEXION",
    "login_Textoformulario_email":"Courrier",
    "login_Textoformulario":"CLÉ",
    "login_PlaceHolder_Ingrese_email":"Saisir l'adresse e-mail",
    "login_PlaceHolder_Ingrese_clave":"Saisir le mot de passe",
    "login_link_CrearUnaNuevaCuenta":" Créer un nouveau compte",
    "login_link_olvidaste_tu_clave": "Mot de passe oublié?",
    "login_btn_Ingresar": "Entrer",
    "login_btn_ElegirUsuario": "CHOISISSEZ L'UTILISATEUR",
    "login_Mensaje_IngresarMailvalido":"Veuillez saisir un e-mail valide",
    "login_Mensaje_claveMas6Caracteres":"Votre mot de passe doit contenir plus de 6 caractères",
    "________________________________":"",
    "tipo-registro_titulo_tiporegistro":"Type d'enregistrement",
    "tipo-registro_btn_clienteRegistrado":"Client enregistré",
    "tipo_Registro_btn_clienteAnonimo":"Client anonyme",
    "_____________________________":"",
    "Alta-Cliente_Titulo":"Load Client",
    "Alta-Cliente_Formulario_Texto_Nombre":"Prénom ",
    "Alta-Cliente_Formulario_Texto_Apellido":"Nom",
    "Alta-Cliente_Formulario_Texto_DNI":"DNI",
    "Alta-Cliente_Formulario_Texto_Correo":"Courrier ",
    "Alta-Cliente_Formulario_Texto_Clave":"mot de passe",
    "Alta-Cliente_Formulario_PlaceHolder_Nombre":"Nom",
    "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Entrer le nom de famille",
    "Alta-Cliente_Formulario_PlaceHolder_DNI":"Entrez l'ID",
    "Alta-Cliente_Formulario_PlaceHolder_Correo":"Entrer le courrier",
    "Alta-Cliente_Formulario_PlaceHolder_Clave":"Entrer le mot de passe",
    "Alta-Cliente_btn_Scannear_DNI":"numériser un document",
    "Alta-Cliente_btn_Guardar":"sauvegarder",
    "______________________________":"",
    "alta-duenio_Titulo":"Télécharger le propriétaire / superviseur",
    "alta-duenio_Formulario_Nombre":"Nom",
    "alta-duenio_Formulario_Apellido":"le nom",
    "alta-duenio_Formulario_Cuil":"CUIL",
    "alta-duenio_Formulario_Correo":"courir",
    "alta-duenio_Formulario_TipoDeEmpleado":"Type d'employé",
    "alta-duenio_Formulario_Select_OptionSupervisor":"Superviseur",
    "alta-duenio_Formulario_Select_OptionDuenio":"Propriétaire",
    "alta-duenio_Formulario_BTN_ScannerDNI":"analyse",
    "alta-duenio_Formulario_BTN_Guardar":"sauvegarder",
    "alta-duenio_Listado_Perfil":"Profil",
    "alta-duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta-empleado_Titulo":"Ajouter un employé",
    "alta-empleado_Formulario_Nombre":"Nom",
    "alta-empleado_Formulario_Apellido":"Le nom",
    "alta-empleado_Formulario_Cuil":"CUIL",
    "alta-empleado_Formulario_Correo":"courir",
    "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Ingreser DNI",
    "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Ingreser CUIL",
    "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Ingresar Correo",
    "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Entrer le courrier",
    "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Sélectionnez le type d'employés",
    "alta-empleado_Formulario_BTN_ScannerDNI":"numériser un document",
    "alta-empleado_Formulario_BTN_Guardar":"sauvegarder",
    "Alta-empleado_Formulario_Option_Cocinero":"patron",
    "Alta-empleado_Formulario_Option_Bartender":"Barman",
    "Alta-empleado_Formulario_Option_Mozo":"serveur",
    "Alta-empleado_ListadoFormulario_Perfil":"Profil",
    "Alta-empleado_ListadoFormulario_Empleado":"Employé",

    "_______________________________":"",
    "alta-anonimo_titulo":"Télécharger un client anonyme ",
    "alta-anonimo_TextoFormulario_nombre":"Nom",
    "alta-anonimo_TextoFormularioCorreo":"Correo",
    "alta-anonimo_PlaceHolderNombre":"Entrez le nom",
    "alta-anonimo_PlaceHolderCorreo":"Entrer le courrier",
    "alta-anonimo_PlaceHolderIngreseClave":"Entrer le mot de passe",
    "__________________________________":"",
    "alta-mesa_titulo":"mois de chargement ",
    "alta-mesa_TextoFormulario_codigo_de_mesa":"Code de table",
    "alta-mesa_TextoFormulario_cantidad_de_personas":"Quantité de personnes",
    "alta-mesa_TextoFormulario_tipo_de_mesa":"Type de table",
    "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Sélectionnez le type de table ",
    "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Seleccionar cantidad de personas",
    "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Entrez le code de la table",
    "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta-mesa_TextoFormulario_select_Option_Fumadores":"les fumeurs",
    "alta-mesa_TextoFormulario_select_Option_Discapacitados":"désactivé",
    "alta-mesa_TextoFormulario_select_Option_Normal":"Ordinaire",
    "alta-mesa_btn_Cancelar":"Annuler",
    "alta-mesa_btn_Aceptar":"Accepter",
    "alta-mesa_Listado_Estado":"Etat",



    "___________________________________":"",

    "home_btn_CreatuPedido": "CRÉEZ VOTRE COMMANDE",
    "home_btn_ListadoComida":"LISTE DES ALIMENTS",
    "home_btn_ReservaCliente":"RESERVA CLIENTE",
    "home_btn_CargarMesa":"TABLEAU DE CHARGE",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRMER L'ARRIVÉE DE VOTRE COMMANDE ",
    "home_btn_EscanearCodigo":"scannez votre code",
    "home_btn_AltaEmpeado":"DÉCHARGEMENT DES EMPLOYÉS",
    "home_btn_CargarCliente":"CHARGER LE CLIENT",
    "home_btn_ListadoCliente":"LISTE DES CLIENTS",
    "home_btn_AbrirMesa": "TABLE OUVERTE",
    "home_btn_cerrarMesa": "FERMER LA TABLE",
    "home_btn_TomarPedido":"PRENDRE COMMANDE",
    "home_btn_TomarPedidoCocina":"PRENDRE COMMANDE CUISINE",
    "home_btn_ListadoIngreso":"LISTE DES REVENUS",
    "home_btn_HabilitarReservas":"ACTIVER LES RÉSERVATIONS",
    "home_btn_Hacetudelivery":"HACE TU DELIVERY!",
    "home_btn_Habilitar_Pedido_Delivery":"FAITES VOTRE LIVRAISON!",
    "home_btn_enviar_Pedido":"ENVOYER LA COMMANDE",
    "home_btn_chat":"BAVARDER",
    "home_btn_encuesta_empleado":"SONDAGE AUPRÈS DES EMPLOYÉS",
    "home_btn_Cargar_Ciente":"CHARGER LE CLIENT",
    "home_btn_tomar_pedido_bar":"BARRE DES COMMANDES",
    "__________________________":"",
    "comida-list_titulo":"Liste de nourriture",
    "comida-list_subtitulo":"Cartes alimentaires",
    "comida-list_bebidas":"LETTRES DE BOISSON",
    "comida-list_postre":"LETTRES DE DESSERT",

    "comida-list_Precio":"Prix",
    "________________________":"",
    "comida-detail_Titulo":"La description",
    "comida-detail_Descripcion":"La description",
    "comida-detail_Precio":"Prix",
    "comida-detail_Tiempo":"Temps",
    "________________":"",
    "comida-create_Titulo":"Charger la nourriture",
    "comida-create_FormularioTextNombre":"Nom",
    "comida-create_FormularioTextCodigo":"Code",
    "comida-create_FormularioTextDescripcion":"La description",
    "comida-create_FormularioTextPrecio":"Prix",
    "comida-create_FormularioTextPreparacion":"Préparation",
    "comida-create_FormularioTextTipoDeProducto":"Type de produit",
    "comida-create_PlaceHolder_NombreDeComida":"Nom de l'aliment",
    "comida-create_PlaceHolder_Codigo":"Code alimentaire ",
    "comida-create_PlaceHolder_Descripcion":"Qu'est que c'est?",
    "comida-create_PlaceHolder_CuantoCuesta":"Combien ça coûte?",
    "comida-create_PlaceHolder_CuantoTardaenHacerce":"Combien de temps cela prend-il?",
    "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Sélectionner le genre ",
    "comida-create_Select_PlaceHolder_Comida":"Aliments",
    "comida-create_Select_PlaceHolder_Bebida":"Boisson",
    "comida-create_Select_PlaceHolder_Postre":"Dessert",
    "comida-create_Select_Boton_Cancelar":"Annuler",
    "comida-create_Select_Boton_Aceptar":"Accepter",
    "_______________________":"",
    "listado-cliente_Titulo":"Liste des clients",
    "listado-cliente_formulario":"Profil",
    "_____________________________________":"",
    "abrir-mesa_titulo":"Table ouverte",
    "abrir-mesa_btn_limpiarDatos":"Nettoyer les données",
    "abrir-mesa_select_option_estado":"Etat",
    "abrir-mesa_select_option_cliente":"client",
    "abrir-mesa_select_option_ocupado":"occupé",
    "abrir-mesa_select_option_disponible":"disponible",
    "abrir-mesa_select_option_reservada":"réservé",
    "abrir-mesa_btn_cancelar":"Annuler",
    "abrir-mesa_btn_aceptar":"Accepter",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Télécharger la commande",
    "tomarpedidos_listosParaEntregar":"Prêt à livrer",
    "tomarpedidos_pendientes_de_aprobacion":"Ordres en attente d'approbation",
    "______________________________________--_____":"",
    "ingreso_Titulo ":"liste d'attente",
    "ingreso-cliente_en_espera":"client en attentea",
    "ingreso-estado":"Etat",
    "ingreso-btn-confirmarIngreso":"Confirmer la connexion",
    "ingreso-btn-DenegarAcceso":"Refuser l'accès",
    "______________________________________--__________":"",
    "Habilitar-Reservas_Titulo ":"Activer les réservations",
    "Habilitar-Reservas_Fecha ":"Date",
    "Habilitar-Reservas_Hora ":"Heure",
    "Habilitar-Reservas_Usuario ":"Utilisateur",
    "Habilitar-Reservas_Cantidad_de_Personas ":"Quantité de personnes",
    "Habilitar-Reservas_Mesa ":"Table",
    "Habilitar-Btn-Habilitar ":"Activer",
    "Habilitar-Btn-Rechazar ":"Refuser",
    "Habilitar-option-Cancelar ":"Annuler",
    "Habilitar-option-Aceptar":"Accepter"


 }];
  public arrayINGLES:any=[{
    "login_titulo_login":"SIGN IN",
    "login_Textoformulario_email":"EMAIL",
    "login_Textoformulario":"PASSWORD",
    "login_PlaceHolder_Ingrese_email":"Enter email",
    "login_PlaceHolder_Ingrese_clave":"Enter password",
    "login_link_CrearUnaNuevaCuenta":"Create a New Account",
    "login_link_olvidaste_tu_clave": "Forgot your password?",
    "login_btn_Ingresar": "ENTER",
    "login_btn_ElegirUsuario": "CHOOSE USER",
    "login_Mensaje_IngresarMailvalido":"Please enter a valid email",
    "login_Mensaje_claveMas6Caracteres":"Your password must have more than 6 characters",
    
    "________________________________":"",
    "tipo-registro_titulo_tiporegistro":"Registration Type",
    "tipo-registro_btn_clienteRegistrado":"Registered CustomeR",
    "tipo_Registro_btn_clienteAnonimo":"Anonymous Client",
    "_____________________________":"",
    "Alta-Cliente_Titulo":"Load Client ",
    "Alta-Cliente_Formulario_Texto_Nombre":"First name",
    "Alta-Cliente_Formulario_Texto_Apellido":"Last Name",
    "Alta-Cliente_Formulario_Texto_DNI":"DNI",
    "Alta-Cliente_Formulario_Texto_Correo":"Email",
    "Alta-Cliente_Formulario_Texto_Clave":"Password",
    "Alta-Cliente_Formulario_PlaceHolder_Nombre":"Name",
    "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Enter Last Name",
    "Alta-Cliente_Formulario_PlaceHolder_DNI":"Enter DNI",
    "Alta-Cliente_Formulario_PlaceHolder_Correo":"Enter Mail",
    "Alta-Cliente_Formulario_PlaceHolder_Clave":"Enter Password",
    "Alta-Cliente_btn_Scannear_DNI":"Scan DNI",
    "Alta-Cliente_btn_Guardar":"Save",
    "______________________________":"",
    "alta-duenio_Titulo":"Load Owner / Inspector",
    "alta-duenio_Formulario_Nombre":"First Name",
    "alta-duenio_Formulario_Apellido":"Last Name",
    "alta-duenio_Formulario_Cuil":"CUIL",
    "alta-duenio_Formulario_Correo":"Mail",
    "alta-duenio_Formulario_TipoDeEmpleado":"Employee Type",
    "alta-duenio_Formulario_Select_OptionSupervisor":"Inspector",
    "alta-duenio_Formulario_Select_OptionDuenio":"Owner",
    "alta-duenio_Formulario_BTN_ScannerDNI":"Scanner",
    "alta-duenio_Formulario_BTN_Guardar":"Save",
    "alta-duenio_Listado_Perfil":"Profile",
    "alta-duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta-empleado_Titulo":"Add Employee",
    "alta-empleado_Formulario_Nombre":"First name",
    "alta-empleado_Formulario_Apellido":"Last name",
    "alta-empleado_Formulario_Cuil":"CUIL",
    "alta-empleado_Formulario_Correo":"Mail",
    "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Enter DNI",
    "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Enter CUIL",
    "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Enter Mail",
    "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Employee Type",
    "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Select type of employees",
    "alta-empleado_Formulario_BTN_ScannerDNI":"Scan DNI",
    "alta-empleado_Formulario_BTN_Guardar":"SAVE",
    "Alta-empleado_Formulario_Option_Cocinero":"Cook",
    "Alta-empleado_Formulario_Option_Bartender":"Bartender",
    "Alta-empleado_Formulario_Option_Mozo":"Mozo",
    "Alta-empleado_ListadoFormulario_Perfil":"Profile",
    "Alta-empleado_ListadoFormulario_Empleado":"Employee",

    "_______________________________":"",
    "alta-anonimo_titulo":"Load Anonymous Client",
    "alta-anonimo_TextoFormulario_nombre":"Name ",
    "alta-anonimo_TextoFormularioCorreo":"Mail ",
    "alta-anonimo_PlaceHolderNombre":"Enter Name",
    "alta-anonimo_PlaceHolderCorreo":" Enter Mail",
    "alta-anonimo_PlaceHolderIngreseClave":"Enter Password ",
    "__________________________________":"",
    "alta-mesa_titulo":"Load Table",
    "alta-mesa_TextoFormulario_codigo_de_mesa":"Table Code",
    "alta-mesa_TextoFormulario_cantidad_de_personas":"Number of People",
    "alta-mesa_TextoFormulario_tipo_de_mesa":"Table Type",
    "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Select Table Type",
    "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Select Number of People",
    "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Enter table code",
    "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta-mesa_TextoFormulario_select_Option_Fumadores":"Smokers",
    "alta-mesa_TextoFormulario_select_Option_Discapacitados":"Disabled",
    "alta-mesa_TextoFormulario_select_Option_Normal":"Normal",
    "alta-mesa_btn_Cancelar":"Cancel",
    "alta-mesa_btn_Aceptar":"Aceptar",
    "alta-mesa_Listado_Estado":"State",
    "___________________________________":"",

    "home_btn_CreatuPedido": "CREATE YOUR ORDER",
    "home_btn_ListadoComida":"LIST OF FOODS",
    "home_btn_ReservaCliente":"BOOK CUSTOMER ",
    "home_btn_CargarMesa":"LOAD TABLE",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRM THE ARRIVAL OF YOUR ORDER",
    "home_btn_EscanearCodigo":"SCAN YOUR CODE",
    "home_btn_AltaEmpeado":"EMPLOYEE REGISTRATION",
    "home_btn_CargarCliente":"LOAD CUSTOMER",
    "home_btn_ListadoCliente":"CLIENT LIST",
    "home_btn_AbrirMesa": "OPEN TABLE",
    "home_btn_cerrarMesa": "CLOSE TABLE",
    "home_btn_TomarPedido":"TAKE ORDER",
    "home_btn_TomarPedidoCocina":"TAKE KITCHEN ORDER",
    "home_btn_ListadoIngreso":"ENTRY LISTING",
    "home_btn_HabilitarReservas":"ENABLE RESERVES",
    "home_btn_Hacetudelivery":"MAKE YOUR DELIVERY!",
    "home_btn_Habilitar_Pedido_Delivery":"ENABLE ORDER DELIVERY",
    "home_btn_enviar_Pedido":"SEND ORDER",
    "home_btn_chat":"CHAT",
    "home_btn_encuesta_empleado":"EMPLOYEE SURVEY",
    "home_btn_Cargar_Ciente":"LOAD CUSTOMER",
    "home_btn_tomar_pedido_bar":"TAKE BAR ORDERS",
    "__________________________":"",
    "comida-list_titulo":"TAKE BAR ORDERS",
    "comida-list_subtitulo":"FOOD LETTERS",
    "comida-list_bebidas":"BEVERAGE LETTERS",
    "comida-list_postre":"DESSERT LETTERS",
    "comida-list_Precio":"Price",
    "________________________":"",
    "comida-detail_Titulo":"Description",
    "comida-detail_Descripcion":"Description",
    "comida-detail_Precio":"Price",
    "comida-detail_Tiempo":"Time",
    "________________":"",
    "comida-create_Titulo":"Load Food",
    "comida-create_FormularioTextNombre":"Name",
    "comida-create_FormularioTextCodigo":"Code",
    "comida-create_FormularioTextDescripcion":"Description",
    "comida-create_FormularioTextPrecio":"Price",
    "comida-create_FormularioTextPreparacion":"Preparation",
    "comida-create_FormularioTextTipoDeProducto":"Product Type",
    "comida-create_PlaceHolder_NombreDeComida":"Food name",
    "comida-create_PlaceHolder_Codigo":"Food Code",
    "comida-create_PlaceHolder_Descripcion":"What is it?",
    "comida-create_PlaceHolder_CuantoCuesta":"How much does it cost?",
    "comida-create_PlaceHolder_CuantoTardaenHacerce":"How long does it take to make it?",
    "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Select the type",
    "comida-create_Select_PlaceHolder_Comida":"Food",
    "comida-create_Select_PlaceHolder_Bebida":"Drink",
    "comida-create_Select_PlaceHolder_Postre":"Dessert",
    "comida-create_Select_Boton_Cancelar":"Cancel",
    "comida-create_Select_Boton_Aceptar":"Accept",
    "_______________________":"",
    "listado-cliente_Titulo":"List CLient",
    "listado-cliente_formulario":"Profile",
    "_____________________________________":"",
    "abrir-mesa_titulo":"Open Table",
    "abrir-mesa_btn_limpiarDatos":"Clear Date",
    "abrir-mesa_select_option_estado":"Status",
    "abrir-mesa_select_option_cliente":"Client",
    "abrir-mesa_select_option_ocupado":"Busy",
    "abrir-mesa_select_option_disponible":"Available",
    "abrir-mesa_select_option_reservada":"Reserved",
    "abrir-mesa_btn_cancelar":"Cancel",
    "abrir-mesa_btn_aceptar":"Accept",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Load Order",
    "tomarpedidos_listosParaEntregar":"Ready To Deliver",
    "tomarpedidos_pendientes_de_aprobacion":"Pending Orders Approval",
    "______________________________________--_____":"",
    "ingreso_Titulo ":"Waiting List",
    "ingreso-cliente_en_espera":"Client Waiting",
    "ingreso-estado":"Status",
    "ingreso-btn-confirmarIngreso":"Confirm Entry",
    "ingreso-btn-DenegarAcceso":"Deny Access",
    "______________________________________--__________":"",
    "Habilitar-Reservas_Titulo ":"Enable Reservation",
    "Habilitar-Reservas_Fecha ":"Date",
    "Habilitar-Reservas_Hora ":"Time",
    "Habilitar-Reservas_Usuario ":"User",
    "Habilitar-Reservas_Cantidad_de_Personas ":"Number of People",
    "Habilitar-Reservas_Mesa ":"Table",
    "Habilitar-Btn-Habilitar ":"Enable",
    "Habilitar-Btn-Rechazar ":"Reject",
    "Habilitar-option-Cancelar ":"Cancel",
    "Habilitar-option-Aceptar":"Accep"


 }];



 public arrayRusia:any=[{
  "login_titulo_login":"АВТОРИЗОВАТЬСЯ",
  "login_Textoformulario_email":"ЭЛ. АДРЕС",
  "login_Textoformulario":"MOT DE PASSE",
  "login_PlaceHolder_Ingrese_email":"Введите адрес электронной почты",
  "login_PlaceHolder_Ingrese_clave":"Введите пароль",
  "login_link_CrearUnaNuevaCuenta":"Создать новый аккаунт",
  "login_link_olvidaste_tu_clave": "Забыли Ваш пароль?",
  "login_btn_Ingresar": "Залезай",
  "login_btn_ElegirUsuario": "ВЫБЕРИТЕ ПОЛЬЗОВАТЕЛЯ",
  "login_Mensaje_IngresarMailvalido":"Пожалуйста, введите действительный адрес электронной почты",
  "login_Mensaje_claveMas6Caracteres":"Ваш пароль должен содержать более 6 символов",

  "________________________________":"",
  "tipo-registro_titulo_tiporegistro":"тип регистра",
  "tipo-registro_btn_clienteRegistrado":"Зарегистрированный клиент",
  "tipo_Registro_btn_clienteAnonimo":"Анонимный клиент",
  "_____________________________":"",
  "Alta-Cliente_Titulo":"Загрузить клиент",
  "Alta-Cliente_Formulario_Texto_Nombre":"название",
  "Alta-Cliente_Formulario_Texto_Apellido":"Фамилия",
  "Alta-Cliente_Formulario_Texto_DNI":"DNI",
  "Alta-Cliente_Formulario_Texto_Correo":"почта",
  "Alta-Cliente_Formulario_Texto_Clave":"ключ",
  "Alta-Cliente_Formulario_PlaceHolder_Nombre":"название",
  "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Введите фамилию",
  "Alta-Cliente_Formulario_PlaceHolder_DNI":"Введите DNI",
  "Alta-Cliente_Formulario_PlaceHolder_Correo":"Введите почту",
  "Alta-Cliente_Formulario_PlaceHolder_Clave":"Введите пароль",
  "Alta-Cliente_btn_Scannear_DNI":"сканирование днни",
  "Alta-Cliente_btn_Guardar":"спасти",
  "______________________________":"",
  "alta-duenio_Titulo":"Загрузить владельца / руководителя",
  "alta-duenio_Formulario_Nombre":"название",
  "alta-duenio_Formulario_Apellido":"Фамилия",
  "alta-duenio_Formulario_Cuil":"CUIL",
  "alta-duenio_Formulario_Correo":"почта",
  "alta-duenio_Formulario_TipoDeEmpleado":"Тип сотрудника",
  "alta-duenio_Formulario_Select_OptionSupervisor":"Руководитель",
  "alta-duenio_Formulario_Select_OptionDuenio":"владелец",
  "alta-duenio_Formulario_BTN_ScannerDNI":"сканирование",
  "alta-duenio_Formulario_BTN_Guardar":"спасти",
  "alta-duenio_Listado_Perfil":"Профиль",
  "alta-duenio_Listado_DNI":"DNI",
  "________________Altaempleado_____________________":"",
  "alta-empleado_Titulo":"Добавить сотрудника",
  "alta-empleado_Formulario_Nombre":"название",
  "alta-empleado_Formulario_Apellido":"Фамилия",
  "alta-empleado_Formulario_Cuil":"CUIL",
  "alta-empleado_Formulario_Correo":"почта",
  "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Введите DNI",
  "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Введите CUIL",
  "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Введите почту",
  "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Тип сотрудника",
  "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Выберите тип сотрудников",
  "alta-empleado_Formulario_BTN_ScannerDNI":"Сканирование DNI",
  "alta-empleado_Formulario_BTN_Guardar":"спасти",
  "Alta-empleado_Formulario_Option_Cocinero":"шеф-повар",
  "Alta-empleado_Formulario_Option_Bartender":"буфетчик",
  "Alta-empleado_Formulario_Option_Mozo":"Официант",
  "Alta-empleado_ListadoFormulario_Perfil":"Профиль",
  "Alta-empleado_ListadoFormulario_Empleado":"Наемный рабочий",

  "_______________________________":"",
  "alta-anonimo_titulo":"Загрузить анонимный клиент",
  "alta-anonimo_TextoFormulario_nombre":"название",
  "alta-anonimo_TextoFormularioCorreo":"почта",
  "alta-anonimo_PlaceHolderNombre":"Введите имя",
  "alta-anonimo_PlaceHolderCorreo":"Введите почту",
  "alta-anonimo_PlaceHolderIngreseClave":"Введите пароль",
  "__________________________________":"",
  "alta-mesa_titulo":"Загрузить таблицу",
  "alta-mesa_TextoFormulario_codigo_de_mesa":"Код таблицы",
  "alta-mesa_TextoFormulario_cantidad_de_personas":"Количество людей",
  "alta-mesa_TextoFormulario_tipo_de_mesa":"Тип таблицы",
  "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Выберите тип таблицы",
  "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Выберите количество людей",
  "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Введите код таблицы",
  "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
  "alta-mesa_TextoFormulario_select_Option_Fumadores":"Курильщики",
  "alta-mesa_TextoFormulario_select_Option_Discapacitados":"Отключено",
  "alta-mesa_TextoFormulario_select_Option_Normal":"Нормальный",
  "alta-mesa_btn_Cancelar":"Отмена",
  "alta-mesa_btn_Aceptar":"Принять",
  "alta-mesa_Listado_Estado":"Принять",



  "___________________________________":"",

  "home_btn_CreatuPedido": "СОЗДАЙ СВОЙ ЗАКАЗ",
  "home_btn_ListadoComida":"ПИЩЕВОЙ СПИСОК",
  "home_btn_ReservaCliente":"БРОНИРОВАНИЕ КЛИЕНТА",
  "home_btn_CargarMesa":"ЗАГРУЗИТЬ СТОЛ",
  "home_btn_ConfirmarLLegadaPedido":"ПОДТВЕРЖДАЙТЕ ПРИБЫТИЕ ВАШЕГО ЗАКАЗА",
  "home_btn_EscanearCodigo":"Сканирование вашего кода",
  "home_btn_AltaEmpeado":"Увольнение сотрудника",
  "home_btn_CargarCliente":"ЗАГРУЗИТЬ ЗАКАЗЧИКА",
  "home_btn_ListadoCliente":"СПИСОК КЛИЕНТОВ",
  "home_btn_AbrirMesa": "ОТКРЫТЫЙ СТОЛ",
  "home_btn_cerrarMesa": "ЗАКРЫТЬ СТОЛA",
  "home_btn_TomarPedido":"ПРИНЯТЬ ЗАКАЗ",
  "home_btn_TomarPedidoCocina":"ЗАКАЗАТЬ КУХНЮ",
  "home_btn_ListadoIngreso":"СПИСОК ДОХОДОВ",
  "home_btn_HabilitarReservas":"РАЗРЕШИТЬ БРОНИРОВАНИЕ",
  "home_btn_Hacetudelivery":"ДЕЛАЙ СВОЮ ДОСТАВКУ!",
  "home_btn_Habilitar_Pedido_Delivery":"ВКЛЮЧИТЬ ПОРЯДОК ДОСТАВКИ",
  "home_btn_enviar_Pedido":"ОТПРАВИТЬ ЗАКАЗ ",
  "home_btn_chat":"ЧАТ",
  "home_btn_encuesta_empleado":"ОБСЛУЖИВАНИЕ СОТРУДНИКОВ",
  "home_btn_Cargar_Ciente":"ЗАГРУЗИТЬ ЗАКАЗЧИКА",
  "home_btn_tomar_pedido_bar":"ЗАКАЗАТЬ БАР",
  "__________________________":"",
  "comida-list_titulo":"ЗАКАЗАТЬ БАР",
  "comida-list_subtitulo":"ПИЩЕВЫЕ ПИСЬМА",
  "comida-list_bebidas":"НАПИТКИ",
  "comida-list_postre":"ДЕСЕРТНЫЕ ПИСЬМА",

  "comida-list_Precio":"Цена",
  "________________________":"",
  "comida-detail_Titulo":"Описание",
  "comida-detail_Descripcion":"Описание",
  "comida-detail_Precio":"Цена",
  "comida-detail_Tiempo":"Погода",
  "________________":"",
  "comida-create_Titulo":"Загрузить еду",
  "comida-create_FormularioTextNombre":"название",
  "comida-create_FormularioTextCodigo":"Код",
  "comida-create_FormularioTextDescripcion":"Описание",
  "comida-create_FormularioTextPrecio":"Цена",
  "comida-create_FormularioTextPreparacion":"подготовка",
  "comida-create_FormularioTextTipoDeProducto":"Вид продукта",
  "comida-create_PlaceHolder_NombreDeComida":"Название еды",
  "comida-create_PlaceHolder_Codigo":"Код питания",
  "comida-create_PlaceHolder_Descripcion":"Что это?",
  "comida-create_PlaceHolder_CuantoCuesta":"Сколько?",
  "comida-create_PlaceHolder_CuantoTardaenHacerce":"Сколько времени это занимает?",
  "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Выберите тип ",
  "comida-create_Select_PlaceHolder_Comida":"питание",
  "comida-create_Select_PlaceHolder_Bebida":"Пить",
  "comida-create_Select_PlaceHolder_Postre":"Десерт",
  "comida-create_Select_Boton_Cancelar":"Отмена",
  "comida-create_Select_Boton_Aceptar":"Принять",
  "_______________________":"",
  "listado-cliente_Titulo":"Список клиентов",
  "listado-cliente_formulario":"Профиль",
  "_____________________________________":"",
  "abrir-mesa_titulo":"Открытый стол",
  "abrir-mesa_btn_limpiarDatos":"Чистые данные",
  "abrir-mesa_select_option_estado":"штат",
  "abrir-mesa_select_option_cliente":"клиент",
  "abrir-mesa_select_option_ocupado":"занятый",
  "abrir-mesa_select_option_disponible":"доступный",
  "abrir-mesa_select_option_reservada":"зарезервированный",
  "abrir-mesa_btn_cancelar":"Отмена",
  "abrir-mesa_btn_aceptar":"принять",
  "___________________________________________":"",
  "tomarpedidos_titulo":"Загрузить заказ",
  "tomarpedidos_listosParaEntregar":"Готовы доставить",
  "tomarpedidos_pendientes_de_aprobacion":"Заказы, ожидающие утверждения",
  "______________________________________--_____":"",
  "ingreso_Titulo ":"Лист ожидания",
  "ingreso-cliente_en_espera":"ожидание клиента",
  "ingreso-estado":"штат",
  "ingreso-btn-confirmarIngreso":"Подтвердите логин",
  "ingreso-btn-DenegarAcceso":"Запретить доступ",
  "______________________________________--__________":"",
  "Habilitar-Reservas_Titulo ":"Включить бронирование",
  "Habilitar-Reservas_Fecha ":"Дата",
  "Habilitar-Reservas_Hora ":"Час",
  "Habilitar-Reservas_Usuario ":"пользователь",
  "Habilitar-Reservas_Cantidad_de_Personas ":"Количество людей",
  "Habilitar-Reservas_Mesa ":"Стол",
  "Habilitar-Btn-Habilitar ":"включить",
  "Habilitar-Btn-Rechazar ":"Отказаться",
  "Habilitar-option-Cancelar ":"Отмена",
  "Habilitar-option-Aceptar":"Принять"


}];


public arrayPor: any =[
{
  "login_titulo_login":"INICIAR SESSÃO",
  "login_Textoformulario_email":"CORREIO ELETRÔNICO",
  "login_Textoformulario":"CHAVE",
  "login_PlaceHolder_Ingrese_email":"Introduzir email",
  "login_PlaceHolder_Ingrese_clave":"Digite a senha",
  "login_link_CrearUnaNuevaCuenta":"Criar uma nova conta",
  "login_link_olvidaste_tu_clave": "Esqueceu sua senha?",
  "login_btn_Ingresar": "ENTRAR",
  "login_btn_ElegirUsuario": "ESCOLHA O USUÁRIO",
  "login_Mensaje_IngresarMailvalido":"Por favor digite um email válido",
  "login_Mensaje_claveMas6Caracteres":"Sua senha deve ter mais de 6 caracteres",

  "________________________________":"",
  "tipo-registro_titulo_tiporegistro":"Tipo Registro",
  "tipo-registro_btn_clienteRegistrado":"Cliente Registrado",
  "tipo_Registro_btn_clienteAnonimo":"Cliente anônimo",
  "_____________________________":"",
  "Alta-Cliente_Titulo":"Carregar cliente",
  "Alta-Cliente_Formulario_Texto_Nombre":"Nome",
  "Alta-Cliente_Formulario_Texto_Apellido":"Sobrenome",
  "Alta-Cliente_Formulario_Texto_DNI":"DNI",
  "Alta-Cliente_Formulario_Texto_Correo":"o email",
  "Alta-Cliente_Formulario_Texto_Clave":"senha",
  "Alta-Cliente_Formulario_PlaceHolder_Nombre":"Nome",
  "Alta-Cliente_Formulario_PlaceHolder_Apellido":"Insira o último nome",
  "Alta-Cliente_Formulario_PlaceHolder_DNI":"Digite DNI",
  "Alta-Cliente_Formulario_PlaceHolder_Correo":"Inserir email",
  "Alta-Cliente_Formulario_PlaceHolder_Clave":"Digite a senha",
  "Alta-Cliente_btn_Scannear_DNI":"Varredura DNI",
  "Alta-Cliente_btn_Guardar":"Salve",
  "______________________________":"",
  "alta-duenio_Titulo":"Carregar proprietário / supervisor",
  "alta-duenio_Formulario_Nombre":"Nome",
  "alta-duenio_Formulario_Apellido":"Sorenome",
  "alta-duenio_Formulario_Cuil":"CUIL",
  "alta-duenio_Formulario_Correo":"o email",
  "alta-duenio_Formulario_TipoDeEmpleado":"Tipo de funcionário",
  "alta-duenio_Formulario_Select_OptionSupervisor":"Supervisor",
  "alta-duenio_Formulario_Select_OptionDuenio":"Proprietário",
  "alta-duenio_Formulario_BTN_ScannerDNI":"Varredura",
  "alta-duenio_Formulario_BTN_Guardar":"Salve",
  "alta-duenio_Listado_Perfil":"Perfil",
  "alta-duenio_Listado_DNI":"DNI",
  "________________Altaempleado_____________________":"",
  "alta-empleado_Titulo":"Adicionar funcionário",
  "alta-empleado_Formulario_Nombre":"Nome",
  "alta-empleado_Formulario_Apellido":"Sobrenome",
  "alta-empleado_Formulario_Cuil":"CUIL",
  "alta-empleado_Formulario_Correo":"O email",
  "Alta-empleado_Formulario_PlaceHolder_IngreseDni":"Digite DNI",
  "Alta-empleado_Formulario_PlaceHolder_IngreseCuil":"Digite CUIL",
  "Alta-empleado_Formulario_PlaceHolder_IngresarCorreo":"Digite O email",
  "Alta-empleado_Formulario_PlaceHolder_TipoEmpleado":"Tipo de funcionário",
  "Alta-empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Selecione o tipo de funcionários",
  "alta-empleado_Formulario_BTN_ScannerDNI":"digitalizar dni",
  "alta-empleado_Formulario_BTN_Guardar":"Salve ",
  "Alta-empleado_Formulario_Option_Cocinero":"Chefe de cozinha",
  "Alta-empleado_Formulario_Option_Bartender":"Barman",
  "Alta-empleado_Formulario_Option_Mozo":"Garçom",
  "Alta-empleado_ListadoFormulario_Perfil":"Perfil",
  "Alta-empleado_ListadoFormulario_Empleado":"Empregado",

  "_______________________________":"",
  "alta-anonimo_titulo":"Carregar cliente anônimo",
  "alta-anonimo_TextoFormulario_nombre":"Nome",
  "alta-anonimo_TextoFormularioCorreo":"Enviar",
  "alta-anonimo_PlaceHolderNombre":"Insira o nome",
  "alta-anonimo_PlaceHolderCorreo":"Inserir email",
  "alta-anonimo_PlaceHolderIngreseClave":"Digite a senha",
  "__________________________________":"",
  "alta-mesa_titulo":"Carregar mêsa",
  "alta-mesa_TextoFormulario_codigo_de_mesa":"Código da tabela",
  "alta-mesa_TextoFormulario_cantidad_de_personas":"Quantidade de pessoas",
  "alta-mesa_TextoFormulario_tipo_de_mesa":"Tipo de tabela",
  "alta-mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Selecionar tipo de tabela",
  "alta-mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Selecione o número de pessoas",
  "alta-mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Digite o código da tabela",
  "alta-mesa_TextoFormulario_select_Option_VIP":"VIP",
  "alta-mesa_TextoFormulario_select_Option_Fumadores":"Fumantes",
  "alta-mesa_TextoFormulario_select_Option_Discapacitados":"Desativado",
  "alta-mesa_TextoFormulario_select_Option_Normal":"Normal",
  "alta-mesa_btn_Cancelar":"Cancelar",
  "alta-mesa_btn_Aceptar":"Aceitar",
  "alta-mesa_Listado_Estado":"Estado",



  "___________________________________":"",

  "home_btn_CreatuPedido": "CRIE SUA ORDEM",
  "home_btn_ListadoComida":"LISTA DE ALIMENTOS",
  "home_btn_ReservaCliente":"RESERVA DE CLIENTE ",
  "home_btn_CargarMesa":"TABELA DE CARGA",
  "home_btn_ConfirmarLLegadaPedido":"CONFIRME A CHEGADA DE SUA ORDEM",
  "home_btn_EscanearCodigo":"VERIFIQUE SEU CÓDIGO",
  "home_btn_AltaEmpeado":"DESCARGA DE FUNCIONÁRIO",
  "home_btn_CargarCliente":"CARREGAR CLIENTE ",
  "home_btn_ListadoCliente":"LISTA DE CLIENTES",
  "home_btn_AbrirMesa": "MESA ABERTA",
  "home_btn_cerrarMesa": "FECHADO ABERTO",
  "home_btn_TomarPedido":"ANOTAR UM PEDIDO",
  "home_btn_TomarPedidoCocina":"COZINHA DE PEDIDO",
  "home_btn_ListadoIngreso":"LISTA DE RENDA",
  "home_btn_HabilitarReservas":"ATIVAR RESERVAS",
  "home_btn_Hacetudelivery":"FAÇA SUA ENTREGA!",
  "home_btn_Habilitar_Pedido_Delivery":"ATIVAR PEDIDO DE ENTREGA",
  "home_btn_enviar_Pedido":"ENVIAR A ORDEM",
  "home_btn_chat":"BATE-PAPO",
  "home_btn_encuesta_empleado":"PESQUISA DE EMPREGADOS",
  "home_btn_Cargar_Ciente":"CARREGAR CLIENTE",
  "home_btn_tomar_pedido_bar":"TAKE ORDERS BAR",
  "__________________________":"",
  "comida-list_titulo":"TOMAR PEDIDOS BAR",
  "comida-list_subtitulo":"CARTAS ALIMENTARES",
  "comida-list_bebidas":"LETRAS DE BEBIDAS",
  "comida-list_postre":"CARTAS DE SOBREMESA",

  "comida-list_Precio":"Preço",
  "________________________":"",
  "comida-detail_Titulo":"Descrição",
  "comida-detail_Descripcion":"Descrição",
  "comida-detail_Precio":"Preço",
  "comida-detail_Tiempo":"Clima",
  "________________":"",
  "comida-create_Titulo":"Carregar Comida",
  "comida-create_FormularioTextNombre":"Nome",
  "comida-create_FormularioTextCodigo":"Código",
  "comida-create_FormularioTextDescripcion":"Descrição",
  "comida-crePreçoate_FormularioTextPrecio":"Preço",
  "comida-create_FormularioTextPreparacion":"Preparação",
  "comida-create_FormularioTextTipoDeProducto":"Tipo de produto",
  "comida-create_PlaceHolder_NombreDeComida":"Nome do alimento",
  "comida-create_PlaceHolder_Codigo":"Código alimentar",
  "comida-create_PlaceHolder_Descripcion":"O que é?",
  "comida-create_PlaceHolder_CuantoCuesta":"Quanto custa?",
  "comida-create_PlaceHolder_CuantoTardaenHacerce":"Quanto tempo leva?",
  "comida-create_Select_PlaceHolder_SeleccioneElTipo":"Selecione o tipo",
  "comida-create_Select_PlaceHolder_Comida":"Comida",
  "comida-create_Select_PlaceHolder_Bebida":"Bebida",
  "comida-create_Select_PlaceHolder_Postre":"Sobremesa",
  "comida-create_Select_Boton_Cancelar":"Cancelar",
  "comida-create_Select_Boton_Aceptar":"Aceitar",
  "_______________________":"",
  "listado-cliente_Titulo":"Lista de clientes",
  "listado-cliente_formulario":"Perfil",
  "_____________________________________":"",
  "abrir-mesa_titulo":"Mesa aberta",
  "abrir-mesa_btn_limpiarDatos":"Dados limpos",
  "abrir-mesa_select_option_estado":"Estado",
  "abrir-mesa_select_option_cliente":"cliente",
  "abrir-mesa_select_option_ocupado":"ocupado",
  "abrir-mesa_select_option_disponible":"acessível",
  "abrir-mesa_select_option_reservada":"reservado",
  "abrir-mesa_btn_cancelar":"cancelar",
  "abrir-mesa_btn_aceptar":"aceitar",
  "___________________________________________":"",
  "tomarpedidos_titulo":"Carregar pedido",
  "tomarpedidos_listosParaEntregar":"Pronto para entregar",
  "tomarpedidos_pendientes_de_aprobacion":"Pedidos com aprovação pendente",
  "______________________________________--_____":"",
  "ingreso_Titulo ":"Lista de Espera",
  "ingreso-cliente_en_espera":"cliente em espera",
  "ingreso-estado":"estado",
  "ingreso-btn-confirmarIngreso":"Confirmar login",
  "ingreso-btn-DenegarAcceso":"Negar acesso",
  "______________________________________--__________":"",
  "Habilitar-Reservas_Titulo ":"Ativar reservas",
  "Habilitar-Reservas_Fecha ":"Encontro",
  "Habilitar-Reservas_Hora ":"Hora",
  "Habilitar-Reservas_Usuario ":"Do utilizador",
  "Habilitar-Reservas_Cantidad_de_Personas ":"Quantidade de Pessoas",
  "Habilitar-Reservas_Mesa ":"Tabela",
  "Habilitar-Btn-Habilitar ":"Habilitar",
  "Habilitar-Btn-Rechazar ":"Recusar",
  "Habilitar-option-Cancelar ":"Cancelar",
  "Habilitar-option-Aceptar":"Aceitar"



}];


}
