import { Component, OnInit } from '@angular/core';
import { LogicService } from '../../app/services/logic.service'
import { IData } from '../../app/services/logic.service'
import { Observable } from "rxjs";
import{PopoverPage} from '../popover/popover.page'
import { PopoverController } from '@ionic/angular';
import { ModalController } from '@ionic/angular';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app_tab1',
  templateUrl: './tab1.page.html',
  styleUrls: ['./tab1.page.scss'],
})



export class Tab1Page implements OnInit {

 

  idiomaSeleccionado:any;

  // ../assets/i18n/en1.json

  ngOnInit() {
    this.idiomaSeleccionado = this.route.snapshot.paramMap.get('id');
    
    switch(this.idiomaSeleccionado) { 
      case 'en': { 
        this.array= this.arrayINGLES;
       break; 
      } 
      case 'rus': { 
         this.array= this.arrayRusia;
         break; 
      } 
      case 'por': { 
        this.array= this.arrayPor;
        break; 
     } 
     case'fr':{
       this.array=this.arrayFra;
       break
     }
     case'esp':{
      this.array=this.arrayEs;
      break
    }

    case'de':{
      this.array=this.arrayDe;
      break
    }
     
     
      
      default: { 
        this.array= this.arrayINGLES;
         break; 
      } 
   } 

 
  }
  constructor(public modalController: ModalController,public popoverController: PopoverController,private route: ActivatedRoute) { 

  

  }
  
  
  popup() {
this.modalController.create({component:PopoverPage}).then((modalElement)=>{
  modalElement.present();
})
  }

  public array:any[];

  public arrayDe:any=[ {
    "HaceTuReserva":"Reservieren Sie!",
"ElegirFecha":"BUCHUNGSDATUM WÄHLEN (JAHR-MONAT-TAG)",
"Hora":"Zeit",
"Minuto":"Minute",

   "Circulo":"Kreis",
   "Barras":"Riegel",
    "Porcentajes": "Prozentsätze",
    "graficos":"Grafik",
    "TODOS":"ALLE FELDER SIND ERFORDERLICH",
    "Turno":"Wende",
    "Manana":"Morgen",
    "Mediodia":"Mittag",
    "Noche":"Nacht",
    "Comorecibioelareadetrabajo": "Wie haben Sie den Arbeitsbereich erhalten?",
    "Impecable":"Tadellos",
    "Limpio":"Gereinigt",
    "Normal":"naturgemäß",
    "sucio":"dreckig",
    "asqueroso":"widerlich",
    "Niveldelimpieza":"Sauberkeitsgrad",
    "CantidaddeFaltasencontradas":"Anzahl der gefundenen Fouls",
    "Comentarios":"Bemerkungen",

    "aqui_tiene_la_cuenta":"Hier ist der Account ...",
    "Seleccionar":"Auswählen",
    "DescuentoPostre":"Dessert Rabatt",
    "Descuento10":"10% Rabatt",
    "DescuentoBebidagratis":"Rabatt Gratis Getränk",
    "Descuento":"Rabatt",
    "PrecioSinDescuento": "Preis ohne Rabatt",
    "Mipropina": "Mein Tipp",
    "TOTAL":"Gesamt",
    "Detalle":"Detail",
    "MostrarTotalConDescuento":"Summe mit Rabatt anzeigen",


      "login_titulo_login":"ANMELDUNG",
      "login_Textoformulario_email":"EMAIL",
      "login_Textoformulario":"Passwort",
      "login_PlaceHolder_Ingrese_email":"Email eingeben",
      "login_PlaceHolder_Ingrese_clave":"Enter_Taste",
      "login_link_CrearUnaNuevaCuenta":"Ein neues Konto erstellen",
      "login_link_olvidaste_tu_clave": "Passwort vergessen?",
      "login_btn_Ingresar": "REINKOMMEN",
      "login_btn_ElegirUsuario": "BENUTZER AUSWÄHLEN",
      "login_Mensaje_IngresarMailvalido":"Bitte geben Sie eine gültige Email_Adresse ein",
      "login_Mensaje_claveMas6Caracteres":"Ihr Passwort muss mehr als 6 Zeichen enthalten",
      "alta_pedido_Entregado" :"Entregado",
     
      "alta_pedido_Seleccione_estado_de_pedido":"Bestellstatus auswählen",
      "alta_pedido_Tipo_de_pedido":"Art der Bestellung",
      "alta_pedido_Seleccione_tipo_de_pedido":"Bestellart auswählen:",
      "alta_pedido_pedido":"Auftrag",
      "alta_pedido_Cuenta":"Rechnung",
      "alta_pedido_Guardar":"sparen",
      "alta_pedido_Precio_total_Pedido":"Gesamtpreis Bestellung",
      "Cantidad": "Menge",
      "Producto":"Produkt",
      "Monto_Acumulado_Mesa":"Tabelle der kumulierten Beträge",
      "Seleccionar":"Auswählen",
      "cargar_pedido":"Bestellung hochladen",
      "Editar_pedido":"Reihenfolge bearbeiten",
      "Estado":"Zustand",
      "Tipo_de_pedido":"Art der Bestellung",

      "________________________________":"",
      "tipo_registro_titulo_tiporegistro":"Aufnahmetyp",
      "tipo_registro_btn_clienteRegistrado":"Registrierter Kunde",
      "tipo_Registro_btn_clienteAnonimo":"Anonymer Kunde",
      "_____________________________":"",
      "Alta_Cliente_Titulo":"Client laden",
      "Alta_Cliente_Formulario_Texto_Nombre":"Name",
      "Alta_Cliente_Formulario_Texto_Apellido":"Nachname",
      "Alta_Cliente_Formulario_Texto_DNI":"DNI",
      "Alta_Cliente_Formulario_Texto_Correo":"Correo",
      "Alta_Cliente_Formulario_Texto_Clave":"Passwort",
      "Alta_Cliente_Formulario_PlaceHolder_Nombre":"Name",
      "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Nachname",
      "Alta_Cliente_Formulario_PlaceHolder_DNI":"Geben Sie DNI ein",
      "Alta_Cliente_Formulario_PlaceHolder_Correo":"Mail eingeben",
      "Alta_Cliente_Formulario_PlaceHolder_Clave":"Passwort eingeben",
      "Alta_Cliente_btn_Scannear_DNI":"DNI scannen",
      "Alta_Cliente_btn_Guardar":"sparen",
      "______________________________":"",
      "alta_duenio_Titulo":"Laden Sie den Eigentümer / Supervisor hoch",
      "alta_duenio_Formulario_Nombre":"Name",
      "alta_duenio_Formulario_Apellido":"Nachname",
      "alta_duenio_Formulario_Cuil":"CUIL",
      "alta_duenio_Formulario_Correo":"Mail",
      "alta_duenio_Formulario_TipoDeEmpleado":"Art des Mitarbeiters",
      "alta_duenio_Formulario_Select_OptionSupervisor":"derOberaufseher",
      "alta_duenio_Formulario_Select_OptionDuenio":"Inhaber",
      "alta_duenio_Formulario_BTN_ScannerDNI":"Dokumente scannen",
      "alta_duenio_Formulario_BTN_Guardar":"sparen",
      "alta_duenio_Listado_Perfil":"Profil",
      "alta_duenio_Listado_DNI":"DNI",
      "________________Altaempleado_____________________":"",
      "alta_empleado_Titulo":"Mitarbeiter hinzufügen",
      "alta_empleado_Formulario_Nombre":"Name",
      "alta_empleado_Formulario_Apellido":"Nachname",
      "alta_empleado_Formulario_Cuil":"CUIL",
      "alta_empleado_Formulario_Correo":"Mail",
      "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Geben Sie DNI ein",
      "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Geben Sie CUIL ein",
      "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Mail eingeben",
      "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Mitarbeitertyp",
      "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Wählen Sie den Mitarbeitertyp aus",
      "alta_empleado_Formulario_BTN_ScannerDNI":"ID scannen",
      "alta_empleado_Formulario_BTN_Guardar":"sparen",
      "Alta_empleado_Formulario_Option_Cocinero":"Koch",
      "Alta_empleado_Formulario_Option_Bartender":"Barmann",
      "Alta_empleado_Formulario_Option_Mozo":"Bedienung",
      "Alta_empleado_ListadoFormulario_Perfil":"Profil",
      "Alta_empleado_ListadoFormulario_Empleado":"Mitarbeiter",
  
      "_______________________________":"",
      "alta_anonimo_titulo":"Laden Sie einen anonymen Client hoch",
      "alta_anonimo_TextoFormulario_nombre":"Name",
      "alta_anonimo_TextoFormularioCorreo":"Mail",
      "alta_anonimo_PlaceHolderNombre":"Name eingeben",
      "alta_anonimo_PlaceHolderCorreo":"Mail eingeben",
      "alta_anonimo_PlaceHolderIngreseClave":"Passwort eingeben",
      "__________________________________":"",
      "alta_mesa_titulo":"Tabelle laden",
      "alta_mesa_TextoFormulario_codigo_de_mesa":"Tabellencode",
      "alta_mesa_TextoFormulario_cantidad_de_personas":"Anzahl von Leuten",
      "alta_mesa_TextoFormulario_tipo_de_mesa":"Tabellentyp",
      "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Wählen Sie den Tabellentyp",
      "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Wählen Sie die Anzahl der Personen",
      "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Geben Sie den Tabellencode ein",
      "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
      "alta_mesa_TextoFormulario_select_Option_Fumadores":"Raucher",
      "alta_mesa_TextoFormulario_select_Option_Discapacitados":"Behindert",
      "alta_mesa_TextoFormulario_select_Option_Normal":"Normal",
      "alta_mesa_btn_Cancelar":"Stornieren",
      "alta_mesa_btn_Aceptar":"Akzeptieren",
      "alta_mesa_Listado_Estado":"Zustand",
      "alta_mesa_Listado_Editar":"Bearbeiten",
  
  
  
      "___________________________________":"",
  
      "home_btn_CreatuPedido": "ERSTELLEN SIE IHRE BESTELLUNG",
      "home_btn_ListadoComida":"LEBENSMITTELLISTE",
      "home_btn_ReservaCliente":"KUNDENRESERVIERUNG",
      "home_btn_CargarMesa":"CARGAR MESA",
      "home_btn_ConfirmarLLegadaPedido":"BESTÄTIGEN SIE DIE ANKUNFT IHRER BESTELLUNG",
      "home_btn_EscanearCodigo":"Scannen Sie Ihren Code",
      "home_btn_AltaEmpeado":"ENTLADUNG DES MITARBEITERS",
      "home_btn_CargarCliente":"KUNDE LADEN",
      "home_btn_ListadoCliente":"KUNDENLISTE",
      "home_btn_AbrirMesa": "OFFENER TISCH",
      "home_btn_cerrarMesa": "TABELLE SCHLIESSEN",
      "home_btn_TomarPedido":"BESTELLEN",
      "home_btn_TomarPedidoCocina":"BESTELLKÜCHE",
      "home_btn_ListadoIngreso":"EINKOMMENSLISTE",
      "home_btn_HabilitarReservas":"RESERVIERUNGEN AKTIVIEREN",
      "home_btn_Hacetudelivery":"Machen Sie Ihre Lieferung!",
      "home_btn_Habilitar_Pedido_Delivery":"LIEFERBESTELLUNG AKTIVIERENY",
      "home_btn_enviar_Pedido":"SENDEN SIE DIE BESTELLUNG",
      "home_btn_chat":"PLAUDERN",
      "home_btn_encuesta_empleado":"MITARBEITERBEFRAGUNG",
      "home_btn_Cargar_Ciente":"KUNDE LADEN",
      "home_btn_tomar_pedido_bar":"BESTELLEN SIE BAR",
      "home_Bienvenido":"herzlich willkommen",

      "__________________________":"",
      "comida_list_titulo":"BESTELLEN SIE BAR",
      "comida_list_subtitulo":"LEBENSMITTELBUCHSTABEN",
      "comida_list_bebidas":"GETRÄNKBUCHSTABEN",
      "comida_list_postre":"DESSERT BRIEFE ",
  
      "comida_list_Precio":"Preis",
      "________________________":"",
      "comida_detail_Titulo":"Beschreibung",
      "comida_detail_Descripcion":"Beschreibung",
      "comida_detail_Precio":"Preis",
      "comida_detail_Tiempo":"Tiempo",
      "________________":"",
      "comida_create_Titulo":"Laden Sie Lebensmittel",
      "comida_create_FormularioTextNombre":"Name",
      "comida_create_FormularioTextCodigo":"Code",
      "comida_create_FormularioTextDescripcion":"Beschreibung",
      "comida_create_FormularioTextPrecio":"Preis",
      "comida_create_FormularioTextPreparacion":"Vorbereitung",
      "comida_create_FormularioTextTipoDeProducto":"Art des Produkts",
      "comida_create_PlaceHolder_NombreDeComida":"Name des Lebensmittels",
      "comida_create_PlaceHolder_Codigo":"Lebensmittelcode",
      "comida_create_PlaceHolder_Descripcion":"Was ist es?",
      "comida_create_PlaceHolder_CuantoCuesta":"Wie viel?",
      "comida_create_PlaceHolder_CuantoTardaenHacerce":"Wie lange dauert es?",
      "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Art auswählen",
      "comida_create_Select_PlaceHolder_Comida":"Essen",
      "comida_create_Select_PlaceHolder_Bebida":"Getränk",
      "comida_create_Select_PlaceHolder_Postre":"Dessert",
      "comida_create_Select_Boton_Cancelar":"Stornieren",
      "comida_create_Select_Boton_Aceptar":"Akzeptieren",
      "_______________________":"",
      "listado_cliente_Titulo":"Klienten Liste",
      "listado_cliente_formulario":"Profil",
      "_____________________________________":"",
      "abrir_mesa_titulo":"Offener Tisch",
      "abrir_mesa_btn_limpiarDatos":"Daten löschens",
      "abrir_mesa_select_option_estado":"Zustand",
      "abrir_mesa_select_option_cliente":"Klient",
      "abrir_mesa_select_option_ocupado":"belegt",
      "abrir_mesa_select_option_disponible":"verfügbar",
      "abrir_mesa_select_option_reservada":"reserviert",
      "abrir_mesa_btn_cancelar":"stornieren",
      "abrir_mesa_btn_aceptar":"akzeptieren",
      "abrir_mesa_mesa":"Tabelle",

      "___________________________________________":"",
      "tomarpedidos_titulo":"Bestellung hochladen",
      "tomarpedidos_listosParaEntregar":"Bestellung hochladen",
      "tomarpedidos_pendientes_de_aprobacion":"Bestellungen bis zur Genehmigung",
      "_____________________________________________":"",
      "ingreso_Titulo ":"Warteliste",
      "ingreso_cliente_en_espera":"wartender Kunde",
      "ingreso_estado":"Zustand",
      "ingreso_btn_confirmarIngreso":"Login bestätigen",
      "ingreso_btn_DenegarAcceso":"Zugriff verweigern",
      "__________________________________________________":"",
      "Habilitar_Reservas_Titulo":"Reservierungen aktivieren",
      "Habilitar_Reservas_Fecha":"Datum",
      "Habilitar_Reservas_Hora":"Stunde",
      "Habilitar_Reservas_Usuario":"Benutzer",
      "Habilitar_Reservas_Cantidad_de_Personas":"Anzahl von Leuten",
      "Habilitar_Reservas_Mesa":"Tabelle",
      "Habilitar_Btn_Habilitar":"Aktivieren",
      "Habilitar_Btn_Rechazar":"Ablehnen",
      "Habilitar_option_Cancelar":"Stornieren",
      "Habilitar_option_Aceptar":"Akzeptieren",
      "___________________________________________________":"",

      "reset_password_titulo ":"Passwort zurücksetzen",
      "reset_password_email ":"Email",
      "reset_password_btn_resetYourPassword ":"Passwort zurücksetzen"
    
    
  
  
   }
  ];


  public arrayEs:any = [{
    "HaceTuReserva":"Hace tu Reserva!",
    "ElegirFecha":"ELIGE FECHA DE RESERVA (AÑO-MES-DIA)",
    "Hora":"Hora",
    "Minuto":"Minuto",

    "Circulo":"Circulo",
    "Barras":"Barras",
    "Porcentajes":"Porcentajes",
    "graficos":"Graficos",
    "TODOS":"TODOS LOS CAMPOS SON OBLIGATORIOS",
    "Turno":"Turno",
    "Manana":"Mañana",
    "Mediodia":"Mediodia",
    "Noche":"Noche",
    "Comorecibioelareadetrabajo": "Como recibió el area de trabajo",
    "Impecable":"Impecable",
    "Limpio":"Limpio",
    "Normal":"Normal",
    "sucio":"sucio",
    "asqueroso":"asqueroso",
    "Niveldelimpieza":"Nivel de limpieza",
    "CantidaddeFaltasencontradas":"Cantidad de Faltas encontradas:",
    "Comentarios":"Comentarios",

    "aqui_tiene_la_cuenta":"Aqui tiene la Cuenta...",
    "Seleccionar":"Seleccionar",
    "DescuentoPostre":"Descuento Postre",
    "Descuento10":"Descuento 10%",
    "DescuentoBebidagratis":"Descuento Bebida gratis",
    "Descuento":"Descuento",
    "PrecioSinDescuento": "Precio Sin Descuento",
    "Mipropina": "Mi Propina",
    "TOTAL":"Total",
    "Detalle":"Detalle",
    "MostrarTotalConDescuento":"Mostrar Total Con Descuento",

    "alta_pedido_Entregado" :"Entregado",
    "alta_pedido_Seleccione_estado_de_pedido":"Seleccione estado de pedido",
    "alta_pedido_Tipo_de_pedido":"Tipo de pedido",
    "alta_pedido_Seleccione_tipo_de_pedido":"Seleccione tipo de pedido:",
    "alta_pedido_pedido":"Pedido",
    "alta_pedido_Cuenta":"Cuenta",
    "alta_pedido_Guardar":"Guardar",
    "alta_pedido_Precio_total_Pedido":"Precio total Pedido",
    "Cantidad": "Cantidad",
    "Producto":"Producto",
    "Monto_Acumulado_Mesa":"Monto Acumulado Mesa",
    "Seleccionar":"Seleccionar",
    "cargar_pedido":"Cargar Pedido",
    "Editar_pedido":"Editar Pedido",
    "Estado":"Estado",
    "Tipo_de_pedido":"Tipo de pedido",

    "login_titulo_login":"INICIAR SESIÓN",
    "login_Textoformulario_email":"CORREO ELECTRONICO",
    "login_Textoformulario":"CLAVE",
    "login_PlaceHolder_Ingrese_email":"Ingrese email",
    "login_PlaceHolder_Ingrese_clave":"Ingrese clave",
    "login_link_CrearUnaNuevaCuenta":"Crear una Nueva Cuenta",
    "login_link_olvidaste_tu_clave": "Olvidaste tu clave?",
    "login_btn_Ingresar": "INGRESAR",
    "login_btn_ElegirUsuario": "ELEGIR USUARIO",
    "login_Mensaje_IngresarMailvalido":"Por favor ingrese un email valido",
    "login_Mensaje_claveMas6Caracteres":"Su clave debe poseer mas de 6 caracteres",

    "________________________________":"",
    "tipo_registro_titulo_tiporegistro":"Tipo Registro",
    "tipo_registro_btn_clienteRegistrado":"Cliente Registrado",
    "tipo_Registro_btn_clienteAnonimo":"Cliente Anonimo",
    "_____________________________":"",
    "Alta_Cliente_Titulo":"Cargar Cliente",
    "Alta_Cliente_Formulario_Texto_Nombre":"Nombre",
    "Alta_Cliente_Formulario_Texto_Apellido":"Apellido",
    "Alta_Cliente_Formulario_Texto_DNI":"DNI",
    "Alta_Cliente_Formulario_Texto_Correo":"Correo",
    "Alta_Cliente_Formulario_Texto_Clave":"Clave",
    "Alta_Cliente_Formulario_PlaceHolder_Nombre":"Nombre",
    "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Ingresar Apellido",
    "Alta_Cliente_Formulario_PlaceHolder_DNI":"Ingresar DNI",
    "Alta_Cliente_Formulario_PlaceHolder_Correo":"Ingresar Correo",
    "Alta_Cliente_Formulario_PlaceHolder_Clave":"Ingreser Clave",
    "Alta_Cliente_btn_Scannear_DNI":"Escanear DNI",
    "Alta_Cliente_btn_Guardar":"Guardar",
    "______________________________":"",
    "alta_duenio_Titulo":"Cargar Dueño/ Supervisor",
    "alta_duenio_Formulario_Nombre":"Nombre",
    "alta_duenio_Formulario_Apellido":"Apellido",
    "alta_duenio_Formulario_Cuil":"CUIL",
    "alta_duenio_Formulario_Correo":"Correo",
    "alta_duenio_Formulario_TipoDeEmpleado":"Tipo de Empleado",
    "alta_duenio_Formulario_Select_OptionSupervisor":"Supervisor",
    "alta_duenio_Formulario_Select_OptionDuenio":"Dueño",
    "alta_duenio_Formulario_BTN_ScannerDNI":"Scannear",
    "alta_duenio_Formulario_BTN_Guardar":"Guardar",
    "alta_duenio_Listado_Perfil":"Perfil",
    "alta_duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta_empleado_Titulo":"Agregar Empleado",
    "alta_empleado_Formulario_Nombre":"Nombre",
    "alta_empleado_Formulario_Apellido":"Apellido",
    "alta_empleado_Formulario_Cuil":"CUIL",
    "alta_empleado_Formulario_Correo":"Correo",
    "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Ingreser DNI",
    "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Ingreser CUIL",
    "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Ingresar Correo",
    "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Tipo de Empleado",
    "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Seleccione tipo de empleados",
    "alta_empleado_Formulario_BTN_ScannerDNI":"Scannear DNI",
    "alta_empleado_Formulario_BTN_Guardar":"Guardar",
    "Alta_empleado_Formulario_Option_Cocinero":"Cocinero",
    "Alta_empleado_Formulario_Option_Bartender":"Bartender",
    "Alta_empleado_Formulario_Option_Mozo":"Mozo",
    "Alta_empleado_ListadoFormulario_Perfil":"Perfil",
    "Alta_empleado_ListadoFormulario_Empleado":"Empleado",

    "_______________________________":"",
    "alta_anonimo_titulo":"Cargar Cliente Anonimo",
    "alta_anonimo_TextoFormulario_nombre":"Nombre",
    "alta_anonimo_TextoFormularioCorreo":"Correo",
    "alta_anonimo_PlaceHolderNombre":"Ingrese Nombre",
    "alta_anonimo_PlaceHolderCorreo":"Ingrese Correo",
    "alta_anonimo_PlaceHolderIngreseClave":"Ingrese Clave",
    "__________________________________":"",
    "alta_mesa_titulo":"Cargar Mesa",
    "alta_mesa_TextoFormulario_codigo_de_mesa":"Codigo de Mesa",
    "alta_mesa_TextoFormulario_cantidad_de_personas":"Cantidad de Personas",
    "alta_mesa_TextoFormulario_tipo_de_mesa":"Tipo de Mesa",
    "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Seleccionar tipo de mesa",
    "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Seleccionar cantidad de personas",
    "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Ingrese codigo de mesa",
    "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta_mesa_TextoFormulario_select_Option_Fumadores":"Fumadores",
    "alta_mesa_TextoFormulario_select_Option_Discapacitados":"Discapacitados",
    "alta_mesa_TextoFormulario_select_Option_Normal":"Normal",
    "alta_mesa_btn_Cancelar":"Cancelar",
    "alta_mesa_btn_Aceptar":"Aceptar",
    "alta_mesa_Listado_Estado":"Estado",
    "alta_mesa_Listado_Editar":"Editar",

    "___________________________________":"",

    "home_btn_CreatuPedido": "CREA TU PEDIDO",
    "home_btn_ListadoComida":"LISTADO DE COMIDAS",
    "home_btn_ReservaCliente":"RESERVA CLIENTE",
    "home_btn_CargarMesa":"CARGAR MESA",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRMANOS LA LLEGADA DE TU PEDIDO",
    "home_btn_EscanearCodigo":"ESCANEAR TU CODIGO",
    "home_btn_AltaEmpeado":"ALTA DE EMPLEADO",
    "home_btn_CargarCliente":"CARGAR CLIENTE",
    "home_btn_ListadoCliente":"LISTADO DE CLIENTE",
    "home_btn_AbrirMesa": "ABRIR MESA",
    "home_btn_cerrarMesa": "CERRAR MESA",
    "home_btn_TomarPedido":"TOMAR PEDIDO",
    "home_btn_TomarPedidoCocina":"TOMAR PEDIDO COCINA",
    "home_btn_ListadoIngreso":"LISTADO DE INGRESO",
    "home_btn_HabilitarReservas":"HABILITAR RESEVAS",
    "home_btn_Hacetudelivery":"HACE TU DELIVERY!",
    "home_btn_Habilitar_Pedido_Delivery":"HABILITAR PEDIDO DELIVERY",
    "home_btn_enviar_Pedido":"ENVIAR PEDIDO",
    "home_btn_chat":"CHAT",
    "home_btn_encuesta_empleado":"ENCUESTA EMPLEADO",
    "home_btn_Cargar_Ciente":"CARGAR CLIENTE",
    "home_btn_tomar_pedido_bar":"TOMAR PEDIDOS BAR",
    "home_Bienvenido":"Bienvenido",

    "__________________________":"",
    "comida_list_titulo":"TOMAR PEDIDOS BAR",
    "comida_list_subtitulo":"CARTAS DE COMIDA",
    "comida_list_bebidas":"CARTAS DE BEBIDAS",
    "comida_list_postre":"CARTAS DE POSTRE",

    "comida_list_Precio":"Precio",
    "________________________":"",
    "comida_detail_Titulo":"Descripción",
    "comida_detail_Descripcion":"Descripción",
    "comida_detail_Precio":"Precio",
    "comida_detail_Tiempo":"Tiempo",
    "________________":"",
    "comida_create_Titulo":"Cargar Comida",
    "comida_create_FormularioTextNombre":"Nombre",
    "comida_create_FormularioTextCodigo":"Codigo",
    "comida_create_FormularioTextDescripcion":"Descripción",
    "comida_create_FormularioTextPrecio":"Precio",
    "comida_create_FormularioTextPreparacion":"Preparacion",
    "comida_create_FormularioTextTipoDeProducto":"Tipo de Producto",
    "comida_create_PlaceHolder_NombreDeComida":"Nombre de comida",
    "comida_create_PlaceHolder_Codigo":"Codigo de comida",
    "comida_create_PlaceHolder_Descripcion":"Que es?",
    "comida_create_PlaceHolder_CuantoCuesta":"Cuanto Cuesta?",
    "comida_create_PlaceHolder_CuantoTardaenHacerce":"Cuanto Tarda en Hacerse?",
    "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Seleccione El tipo",
    "comida_create_Select_PlaceHolder_Comida":"Comida",
    "comida_create_Select_PlaceHolder_Bebida":"Bebida",
    "comida_create_Select_PlaceHolder_Postre":"Postre",
    "comida_create_Select_Boton_Cancelar":"Cancelar",
    "comida_create_Select_Boton_Aceptar":"Aceptar",
    "_______________________":"",
    "listado_cliente_Titulo":"Listado CLiente",
    "listado_cliente_formulario":"Perfil",
    "_____________________________________":"",
    "abrir_mesa_titulo":"Abrir Mesa",
    "abrir_mesa_btn_limpiarDatos":"Limpiar Datos",
    "abrir_mesa_select_option_estado":"estado",
    "abrir_mesa_select_option_cliente":"cliente",
    "abrir_mesa_select_option_ocupado":"ocupado",
    "abrir_mesa_select_option_disponible":"disponible",
    "abrir_mesa_select_option_reservada":"reservada",
    "abrir_mesa_btn_cancelar":"cancelar",
    "abrir_mesa_btn_aceptar":"aceptar",
    "abrir_mesa_mesa":"mesa",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Cargar Pedido",
    "tomarpedidos_listosParaEntregar":"Listo Para entregar",
    "tomarpedidos_pendientes_de_aprobacion":"Pedidos Pendientes de Aprobacion",
    "_____________________________________________":"",
    "ingreso_Titulo":"Lista de Espera",
    "ingreso_cliente_en_espera":"cliente en espera",
    "ingreso_estado":"estado",
    "ingreso_btn_confirmarIngreso":"Confirmar Ingreso",
    "ingreso_btn_DenegarAcceso":"Denegar Acceso",
    "__________________________________________________":"",
    "Habilitar_Reservas_Titulo":"Habilitar Reservas",
    "Habilitar_Reservas_Fecha":"Fecha",
    "Habilitar_Reservas_Hora":"Hora",
    "Habilitar_Reservas_Usuario":"Usuario",
    "Habilitar_Reservas_Cantidad_de_Personas":"Cantidad de Personas",
    "Habilitar_Reservas_Mesa":"Mesa",
    "Habilitar_Btn_Habilitar":"Habilitar",
    "Habilitar_Btn_Rechazar":"Rechazar",
    "Habilitar_option_Cancelar":"Cancelar",
    "Habilitar_option_Aceptar":"Aceptar",
    "___________________________________________________":"",
    "reset_password_titulo ":"Reiniciar Contraseña",
    "reset_password_email ":"Correo Electronico",
    "reset_password_btn_resetYourPassword ":"Reiniciar tu contraseña"

 }];

  public arrayFra:any= [{
    "HaceTuReserva":"Faites votre réservation!",
    "ElegirFecha":"CHOISIR LA DATE DE RÉSERVATION (ANNÉE-MOIS-JOUR)",
    "Hora":"temps",
    "Minuto":"Minuto",

    "Circulo":"cercles",
    "Barras":"Bars",
    "Porcentajes":"Pourcentages",

    "graficos":"Graphique",
    "TODOS":"TOUS LES CHAMPS SONT REQUIS",
    "Turno":"Tour",
    "Manana":"Matin",
    "Mediodia":"Midi",
    "Noche":"Nuit",
    "Comorecibioelareadetrabajo": "Comment avez-vous reçu la zone de travail",
    "Impecable":"Impeccable",
    "Limpio":"Propre",
    "Normal":"Ordinaire",
    "sucio":"sale",
    "asqueroso":"répugnant",
    "Niveldelimpieza":"Niveau de propreté",
    "CantidaddeFaltasencontradas":"Nombre de fautes trouvéess",
    "Comentarios":"commentaires",

    "aqui_tiene_la_cuenta":"Voici le compte ...",
    "Seleccionar":"Pour sélectionner",
    "DescuentoPostre":"Remise sur les desserts",
    "Descuento10":"10% de réduction",
    "DescuentoBebidagratis":"Remise boisson gratuite",
    "Descuento":"Remise",
    "PrecioSinDescuento": "Prix ​​sans remise",
    "Mipropina": "Mon conseil",
    "TOTAL":"Total",
    "Detalle":"Détail",
    "MostrarTotalConDescuento":"Afficher le total avec remise",

    "alta_pedido_Entregado" :"livré",
    "alta_pedido_Seleccione_estado_de_pedido":"Sélectionnez l'état de la commande",
    "alta_pedido_Tipo_de_pedido":"Type de commande",
    "alta_pedido_Seleccione_tipo_de_pedido":"Sélectionnez le type de commande:",
    "alta_pedido_pedido":"Ordre",
    "alta_pedido_Cuenta":"compte",
    "alta_pedido_Guardar":"sauvegarder",
    "alta_pedido_Precio_total_Pedido":"Prix ​​total de la commande",
    "Cantidad": "Quantité",
    "Producto":"produit",
    "Monto_Acumulado_Mesa":"Tableau des montants accumulés",
    "Seleccionar":"Pour sélectionner",
    "cargar_pedido":"Télécharger la commande",
    "Editar_pedido":"Modifier la commande",
    "Estado":"Etat",
    "Tipo_de_pedido":"Type de commande",

    "login_titulo_login":"CONNEXION",
    "login_Textoformulario_email":"Courrier",
    "login_Textoformulario":"CLÉ",
    "login_PlaceHolder_Ingrese_email":"Saisir l'adresse e_mail",
    "login_PlaceHolder_Ingrese_clave":"Saisir le mot de passe",
    "login_link_CrearUnaNuevaCuenta":" Créer un nouveau compte",
    "login_link_olvidaste_tu_clave": "Mot de passe oublié?",
    "login_btn_Ingresar": "Entrer",
    "login_btn_ElegirUsuario": "CHOISISSEZ L'UTILISATEUR",
    "login_Mensaje_IngresarMailvalido":"Veuillez saisir un e_mail valide",
    "login_Mensaje_claveMas6Caracteres":"Votre mot de passe doit contenir plus de 6 caractères",
    "________________________________":"",
    "tipo_registro_titulo_tiporegistro":"Type d'enregistrement",
    "tipo_registro_btn_clienteRegistrado":"Client enregistré",
    "tipo_Registro_btn_clienteAnonimo":"Client anonyme",
    "_____________________________":"",
    "Alta_Cliente_Titulo":"Load Client",
    "Alta_Cliente_Formulario_Texto_Nombre":"Prénom ",
    "Alta_Cliente_Formulario_Texto_Apellido":"Nom",
    "Alta_Cliente_Formulario_Texto_DNI":"DNI",
    "Alta_Cliente_Formulario_Texto_Correo":"Courrier ",
    "Alta_Cliente_Formulario_Texto_Clave":"mot de passe",
    "Alta_Cliente_Formulario_PlaceHolder_Nombre":"Nom",
    "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Entrer le nom de famille",
    "Alta_Cliente_Formulario_PlaceHolder_DNI":"Entrez l'ID",
    "Alta_Cliente_Formulario_PlaceHolder_Correo":"Entrer le courrier",
    "Alta_Cliente_Formulario_PlaceHolder_Clave":"Entrer le mot de passe",
    "Alta_Cliente_btn_Scannear_DNI":"numériser un document",
    "Alta_Cliente_btn_Guardar":"sauvegarder",
    "______________________________":"",
    "alta_duenio_Titulo":"Télécharger le propriétaire / superviseur",
    "alta_duenio_Formulario_Nombre":"Nom",
    "alta_duenio_Formulario_Apellido":"le nom",
    "alta_duenio_Formulario_Cuil":"CUIL",
    "alta_duenio_Formulario_Correo":"courir",
    "alta_duenio_Formulario_TipoDeEmpleado":"Type d'employé",
    "alta_duenio_Formulario_Select_OptionSupervisor":"Superviseur",
    "alta_duenio_Formulario_Select_OptionDuenio":"Propriétaire",
    "alta_duenio_Formulario_BTN_ScannerDNI":"analyse",
    "alta_duenio_Formulario_BTN_Guardar":"sauvegarder",
    "alta_duenio_Listado_Perfil":"Profil",
    "alta_duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta_empleado_Titulo":"Ajouter un employé",
    "alta_empleado_Formulario_Nombre":"Nom",
    "alta_empleado_Formulario_Apellido":"Le nom",
    "alta_empleado_Formulario_Cuil":"CUIL",
    "alta_empleado_Formulario_Correo":"courir",
    "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Ingreser DNI",
    "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Ingreser CUIL",
    "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Ingresar Correo",
    "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Entrer le courrier",
    "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Sélectionnez le type d'employés",
    "alta_empleado_Formulario_BTN_ScannerDNI":"numériser un document",
    "alta_empleado_Formulario_BTN_Guardar":"sauvegarder",
    "Alta_empleado_Formulario_Option_Cocinero":"patron",
    "Alta_empleado_Formulario_Option_Bartender":"Barman",
    "Alta_empleado_Formulario_Option_Mozo":"serveur",
    "Alta_empleado_ListadoFormulario_Perfil":"Profil",
    "Alta_empleado_ListadoFormulario_Empleado":"Employé",

    "_______________________________":"",
    "alta_anonimo_titulo":"Télécharger un client anonyme ",
    "alta_anonimo_TextoFormulario_nombre":"Nom",
    "alta_anonimo_TextoFormularioCorreo":"Correo",
    "alta_anonimo_PlaceHolderNombre":"Entrez le nom",
    "alta_anonimo_PlaceHolderCorreo":"Entrer le courrier",
    "alta_anonimo_PlaceHolderIngreseClave":"Entrer le mot de passe",
    "__________________________________":"",
    "alta_mesa_titulo":"mois de chargement ",
    "alta_mesa_TextoFormulario_codigo_de_mesa":"Code de table",
    "alta_mesa_TextoFormulario_cantidad_de_personas":"Quantité de personnes",
    "alta_mesa_TextoFormulario_tipo_de_mesa":"Type de table",
    "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Sélectionnez le type de table ",
    "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Seleccionar cantidad de personas",
    "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Entrez le code de la table",
    "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta_mesa_TextoFormulario_select_Option_Fumadores":"les fumeurs",
    "alta_mesa_TextoFormulario_select_Option_Discapacitados":"désactivé",
    "alta_mesa_TextoFormulario_select_Option_Normal":"Ordinaire",
    "alta_mesa_btn_Cancelar":"Annuler",
    "alta_mesa_btn_Aceptar":"Accepter",
    "alta_mesa_Listado_Estado":"Etat",
    "alta_mesa_Listado_Editar":"Éditer",


    "___________________________________":"",

    "home_btn_CreatuPedido": "CRÉEZ VOTRE COMMANDE",
    "home_btn_ListadoComida":"LISTE DES ALIMENTS",
    "home_btn_ReservaCliente":"RÉSERVATION CLIENT",
    "home_btn_CargarMesa":"TABLEAU DE CHARGE",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRMER L'ARRIVÉE DE VOTRE COMMANDE ",
    "home_btn_EscanearCodigo":"scannez votre code",
    "home_btn_AltaEmpeado":"DÉCHARGEMENT DES EMPLOYÉS",
    "home_btn_CargarCliente":"CHARGER LE CLIENT",
    "home_btn_ListadoCliente":"LISTE DES CLIENTS",
    "home_btn_AbrirMesa": "TABLE OUVERTE",
    "home_btn_cerrarMesa": "FERMER LA TABLE",
    "home_btn_TomarPedido":"PRENDRE COMMANDE",
    "home_btn_TomarPedidoCocina":"PRENDRE COMMANDE CUISINE",
    "home_btn_ListadoIngreso":"LISTE DES REVENUS",
    "home_btn_HabilitarReservas":"ACTIVER LES RÉSERVATIONS",
    "home_btn_Hacetudelivery":"FAITES VOTRE LIVRAISON!",
    "home_btn_Habilitar_Pedido_Delivery":"FAITES VOTRE LIVRAISON!",
    "home_btn_enviar_Pedido":"ENVOYER LA COMMANDE",
    "home_btn_chat":"BAVARDER",
    "home_btn_encuesta_empleado":"SONDAGE AUPRÈS DES EMPLOYÉS",
    "home_btn_Cargar_Ciente":"CHARGER LE CLIENT",
    "home_btn_tomar_pedido_bar":"BARRE DES COMMANDES",
    "home_Bienvenido":"Bienvenue",

    "__________________________":"",
    "comida_list_titulo":"Liste de nourriture",
    "comida_list_subtitulo":"Cartes alimentaires",
    "comida_list_bebidas":"LETTRES DE BOISSON",
    "comida_list_postre":"LETTRES DE DESSERT",

    "comida_list_Precio":"Prix",
    "________________________":"",
    "comida_detail_Titulo":"La description",
    "comida_detail_Descripcion":"La description",
    "comida_detail_Precio":"Prix",
    "comida_detail_Tiempo":"Temps",
    "________________":"",
    "comida_create_Titulo":"Charger la nourriture",
    "comida_create_FormularioTextNombre":"Nom",
    "comida_create_FormularioTextCodigo":"Code",
    "comida_create_FormularioTextDescripcion":"La description",
    "comida_create_FormularioTextPrecio":"Prix",
    "comida_create_FormularioTextPreparacion":"Préparation",
    "comida_create_FormularioTextTipoDeProducto":"Type de produit",
    "comida_create_PlaceHolder_NombreDeComida":"Nom de l'aliment",
    "comida_create_PlaceHolder_Codigo":"Code alimentaire ",
    "comida_create_PlaceHolder_Descripcion":"Qu'est que c'est?",
    "comida_create_PlaceHolder_CuantoCuesta":"Combien ça coûte?",
    "comida_create_PlaceHolder_CuantoTardaenHacerce":"Combien de temps cela prend_il?",
    "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Sélectionner le genre ",
    "comida_create_Select_PlaceHolder_Comida":"Aliments",
    "comida_create_Select_PlaceHolder_Bebida":"Boisson",
    "comida_create_Select_PlaceHolder_Postre":"Dessert",
    "comida_create_Select_Boton_Cancelar":"Annuler",
    "comida_create_Select_Boton_Aceptar":"Accepter",
    "_______________________":"",
    "listado_cliente_Titulo":"Liste des clients",
    "listado_cliente_formulario":"Profil",
    "_____________________________________":"",
    "abrir_mesa_titulo":"Table ouverte",
    "abrir_mesa_btn_limpiarDatos":"Nettoyer les données",
    "abrir_mesa_select_option_estado":"Etat",
    "abrir_mesa_select_option_cliente":"client",
    "abrir_mesa_select_option_ocupado":"occupé",
    "abrir_mesa_select_option_disponible":"disponible",
    "abrir_mesa_select_option_reservada":"réservé",
    "abrir_mesa_btn_cancelar":"Annuler",
    "abrir_mesa_btn_aceptar":"Accepter",
    "abrir_mesa_mesa":"table",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Télécharger la commande",
    "tomarpedidos_listosParaEntregar":"Prêt à livrer",
    "tomarpedidos_pendientes_de_aprobacion":"Ordres en attente d'approbation",
    "_____________________________________________":"",
    "ingreso_Titulo ":"liste d'attente",
    "ingreso_cliente_en_espera":"client en attentea",
    "ingreso_estado":"Etat",
    "ingreso_btn_confirmarIngreso":"Confirmer la connexion",
    "ingreso_btn_DenegarAcceso":"Refuser l'accès",
    "__________________________________________________":"",
    "Habilitar_Reservas_Titulo":"Activer les réservations",
    "Habilitar_Reservas_Fecha":"Date",
    "Habilitar_Reservas_Hora":"Heure",
    "Habilitar_Reservas_Usuario":"Utilisateur",
    "Habilitar_Reservas_Cantidad_de_Personas":"Quantité de personnes",
    "Habilitar_Reservas_Mesa":"Table",
    "Habilitar_Btn_Habilitar":"Activer",
    "Habilitar_Btn_Rechazar":"Refuser",
    "Habilitar_option_Cancelar":"Annuler",
    "Habilitar_option_Aceptar":"Accepter",
    "___________________________________________________":"",

    "reset_password_titulo ":"réinitialiser le mot de passe",
    "reset_password_email ":"Courrier électronique",
    "reset_password_btn_resetYourPassword ":"Rréinitialiser le mot de passe"
	
	


 }];
  public arrayINGLES:any=[{
    "HaceTuReserva":"Make your Reservation!",
    "ElegirFecha":"CHOOSE BOOKING DATE (YEAR-MONTH-DAY)",
    "Hora":"Time",
    "Minuto":"Minute",
    "Circulo":"Circle",
    "Barras":"Bars",
    "Porcentajes":"Percentages",
    "graficos":"Graphics",
    "TODOS":"ALL FIELDS ARE REQUIRED",
    "Turno":"Turn",
    "Manana":"morning",
    "Mediodia":"Midday",
    "Noche":"Night",
    "Comorecibioelareadetrabajo": "How did you receive the work area",
    "Impecable":"Impeccable",
    "Limpio":"cleansed",
    "Normal":"Normal",
    "sucio":"dirty",
    "asqueroso":"disgusting",
    "Niveldelimpieza":"Cleanliness level",
    "CantidaddeFaltasencontradas":"Amount of fouls found",
    "Comentarios":"Comments",
    
    "aqui_tiene_la_cuenta":"Here's the Account ...",
    "Seleccionar":"To select",
    "DescuentoPostre":"Dessert Discount",
    "Descuento10":"10% discount",
    "DescuentoBebidagratis":"Discount Free Drink",
    "Descuento":"Discount",
    "PrecioSinDescuento": "Price Without Discount",
    "Mipropina": "My tip",
    "TOTAL":"Total",
    "Detalle":"Detail",
    "MostrarTotalConDescuento":"Show Total With Discount",

    "alta_pedido_Entregado" :"Delivered",
    "alta_pedido_Seleccione_estado_de_pedido":"Select order status",
    "alta_pedido_Tipo_de_pedido":"Type of order",
    "alta_pedido_Seleccione_tipo_de_pedido":"Select type of order:",
    "alta_pedido_pedido":"Order",
    "alta_pedido_Cuenta":"Bill",
    "alta_pedido_Guardar":"Save",
    "alta_pedido_Precio_total_Pedido":"Total Price Order",
    "Cantidad": "Quantity",
    "Producto":"Product",
    "Monto_Acumulado_Mesa":"Accumulated Amount Table",
    "Seleccionar":"To select",
    "cargar_pedido":"Upload Order",
    "Editar_pedido":"Edit Order",
    "Estado":"State",
    "Tipo_de_pedido":"Type of order",

    "login_titulo_login":"SIGN IN",
    "login_Textoformulario_email":"EMAIL",
    "login_Textoformulario":"PASSWORD",
    "login_PlaceHolder_Ingrese_email":"Enter email",
    "login_PlaceHolder_Ingrese_clave":"Enter password",
    "login_link_CrearUnaNuevaCuenta":"Create a New Account",
    "login_link_olvidaste_tu_clave": "Forgot your password?",
    "login_btn_Ingresar": "ENTER",
    "login_btn_ElegirUsuario": "CHOOSE USER",
    "login_Mensaje_IngresarMailvalido":"Please enter a valid email",
    "login_Mensaje_claveMas6Caracteres":"Your password must have more than 6 characters",
    
    "________________________________":"",
    "tipo_registro_titulo_tiporegistro":"Registration Type",
    "tipo_registro_btn_clienteRegistrado":"Registered CustomeR",
    "tipo_Registro_btn_clienteAnonimo":"Anonymous Client",
    "_____________________________":"",
    "Alta_Cliente_Titulo":"Load Client ",
    "Alta_Cliente_Formulario_Texto_Nombre":"First name",
    "Alta_Cliente_Formulario_Texto_Apellido":"Last Name",
    "Alta_Cliente_Formulario_Texto_DNI":"DNI",
    "Alta_Cliente_Formulario_Texto_Correo":"Email",
    "Alta_Cliente_Formulario_Texto_Clave":"Password",
    "Alta_Cliente_Formulario_PlaceHolder_Nombre":"Name",
    "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Enter Last Name",
    "Alta_Cliente_Formulario_PlaceHolder_DNI":"Enter DNI",
    "Alta_Cliente_Formulario_PlaceHolder_Correo":"Enter Mail",
    "Alta_Cliente_Formulario_PlaceHolder_Clave":"Enter Password",
    "Alta_Cliente_btn_Scannear_DNI":"Scan DNI",
    "Alta_Cliente_btn_Guardar":"Save",
    "______________________________":"",
    "alta_duenio_Titulo":"Load Owner / Inspector",
    "alta_duenio_Formulario_Nombre":"First Name",
    "alta_duenio_Formulario_Apellido":"Last Name",
    "alta_duenio_Formulario_Cuil":"CUIL",
    "alta_duenio_Formulario_Correo":"Mail",
    "alta_duenio_Formulario_TipoDeEmpleado":"Employee Type",
    "alta_duenio_Formulario_Select_OptionSupervisor":"Inspector",
    "alta_duenio_Formulario_Select_OptionDuenio":"Owner",
    "alta_duenio_Formulario_BTN_ScannerDNI":"Scanner",
    "alta_duenio_Formulario_BTN_Guardar":"Save",
    "alta_duenio_Listado_Perfil":"Profile",
    "alta_duenio_Listado_DNI":"DNI",
    "________________Altaempleado_____________________":"",
    "alta_empleado_Titulo":"Add Employee",
    "alta_empleado_Formulario_Nombre":"First name",
    "alta_empleado_Formulario_Apellido":"Last name",
    "alta_empleado_Formulario_Cuil":"CUIL",
    "alta_empleado_Formulario_Correo":"Mail",
    "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Enter DNI",
    "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Enter CUIL",
    "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Enter Mail",
    "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Employee Type",
    "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Select type of employees",
    "alta_empleado_Formulario_BTN_ScannerDNI":"Scan DNI",
    "alta_empleado_Formulario_BTN_Guardar":"SAVE",
    "Alta_empleado_Formulario_Option_Cocinero":"Cook",
    "Alta_empleado_Formulario_Option_Bartender":"Bartender",
    "Alta_empleado_Formulario_Option_Mozo":"Mozo",
    "Alta_empleado_ListadoFormulario_Perfil":"Profile",
    "Alta_empleado_ListadoFormulario_Empleado":"Employee",

    "_______________________________":"",
    "alta_anonimo_titulo":"Load Anonymous Client",
    "alta_anonimo_TextoFormulario_nombre":"Name ",
    "alta_anonimo_TextoFormularioCorreo":"Mail ",
    "alta_anonimo_PlaceHolderNombre":"Enter Name",
    "alta_anonimo_PlaceHolderCorreo":" Enter Mail",
    "alta_anonimo_PlaceHolderIngreseClave":"Enter Password ",
    "__________________________________":"",
    "alta_mesa_titulo":"Load Table",
    "alta_mesa_TextoFormulario_codigo_de_mesa":"Table Code",
    "alta_mesa_TextoFormulario_cantidad_de_personas":"Number of People",
    "alta_mesa_TextoFormulario_tipo_de_mesa":"Table Type",
    "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Select Table Type",
    "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Select Number of People",
    "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Enter table code",
    "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
    "alta_mesa_TextoFormulario_select_Option_Fumadores":"Smokers",
    "alta_mesa_TextoFormulario_select_Option_Discapacitados":"Disabled",
    "alta_mesa_TextoFormulario_select_Option_Normal":"Normal",
    "alta_mesa_btn_Cancelar":"Cancel",
    "alta_mesa_btn_Aceptar":"Aceptar",
    "alta_mesa_Listado_Estado":"State",
    "alta_mesa_Listado_Editar":"Édit",

    "___________________________________":"",

    "home_btn_CreatuPedido": "CREATE YOUR ORDER",
    "home_btn_ListadoComida":"LIST OF FOODS",
    "home_btn_ReservaCliente":"BOOK CUSTOMER ",
    "home_btn_CargarMesa":"LOAD TABLE",
    "home_btn_ConfirmarLLegadaPedido":"CONFIRM THE ARRIVAL OF YOUR ORDER",
    "home_btn_EscanearCodigo":"SCAN YOUR CODE",
    "home_btn_AltaEmpeado":"EMPLOYEE REGISTRATION",
    "home_btn_CargarCliente":"LOAD CUSTOMER",
    "home_btn_ListadoCliente":"CLIENT LIST",
    "home_btn_AbrirMesa": "OPEN TABLE",
    "home_btn_cerrarMesa": "CLOSE TABLE",
    "home_btn_TomarPedido":"TAKE ORDER",
    "home_btn_TomarPedidoCocina":"TAKE KITCHEN ORDER",
    "home_btn_ListadoIngreso":"ENTRY LISTING",
    "home_btn_HabilitarReservas":"ENABLE RESERVES",
    "home_btn_Hacetudelivery":"MAKE YOUR DELIVERY!",
    "home_btn_Habilitar_Pedido_Delivery":"ENABLE ORDER DELIVERY",
    "home_btn_enviar_Pedido":"SEND ORDER",
    "home_btn_chat":"CHAT",
    "home_btn_encuesta_empleado":"EMPLOYEE SURVEY",
    "home_btn_Cargar_Ciente":"LOAD CUSTOMER",
    "home_btn_tomar_pedido_bar":"TAKE BAR ORDERS",
    "home_Bienvenido":"Welcome",
    "__________________________":"",
    "comida_list_titulo":"TAKE BAR ORDERS",
    "comida_list_subtitulo":"FOOD LETTERS",
    "comida_list_bebidas":"BEVERAGE LETTERS",
    "comida_list_postre":"DESSERT LETTERS",
    "comida_list_Precio":"Price",
    "________________________":"",
    "comida_detail_Titulo":"Description",
    "comida_detail_Descripcion":"Description",
    "comida_detail_Precio":"Price",
    "comida_detail_Tiempo":"Time",
    "________________":"",
    "comida_create_Titulo":"Load Food",
    "comida_create_FormularioTextNombre":"Name",
    "comida_create_FormularioTextCodigo":"Code",
    "comida_create_FormularioTextDescripcion":"Description",
    "comida_create_FormularioTextPrecio":"Price",
    "comida_create_FormularioTextPreparacion":"Preparation",
    "comida_create_FormularioTextTipoDeProducto":"Product Type",
    "comida_create_PlaceHolder_NombreDeComida":"Food name",
    "comida_create_PlaceHolder_Codigo":"Food Code",
    "comida_create_PlaceHolder_Descripcion":"What is it?",
    "comida_create_PlaceHolder_CuantoCuesta":"How much does it cost?",
    "comida_create_PlaceHolder_CuantoTardaenHacerce":"How long does it take to make it?",
    "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Select the type",
    "comida_create_Select_PlaceHolder_Comida":"Food",
    "comida_create_Select_PlaceHolder_Bebida":"Drink",
    "comida_create_Select_PlaceHolder_Postre":"Dessert",
    "comida_create_Select_Boton_Cancelar":"Cancel",
    "comida_create_Select_Boton_Aceptar":"Accept",
    "_______________________":"",
    "listado_cliente_Titulo":"List CLient",
    "listado_cliente_formulario":"Profile",
    "_____________________________________":"",
    "abrir_mesa_titulo":"Open Table",
    "abrir_mesa_btn_limpiarDatos":"Clear Date",
    "abrir_mesa_select_option_estado":"Status",
    "abrir_mesa_select_option_cliente":"Client",
    "abrir_mesa_select_option_ocupado":"Busy",
    "abrir_mesa_select_option_disponible":"Available",
    "abrir_mesa_select_option_reservada":"Reserved",
    "abrir_mesa_btn_cancelar":"Cancel",
    "abrir_mesa_btn_aceptar":"Accept",
    "abrir_mesa_mesa":"table",
    "___________________________________________":"",
    "tomarpedidos_titulo":"Load Order",
    "tomarpedidos_listosParaEntregar":"Ready To Deliver",
    "tomarpedidos_pendientes_de_aprobacion":"Pending Orders Approval",
    "_____________________________________________":"",
    "ingreso_Titulo ":"Waiting List",
    "ingreso_cliente_en_espera":"Client Waiting",
    "ingreso_estado":"Status",
    "ingreso_btn_confirmarIngreso":"Confirm Entry",
    "ingreso_btn_DenegarAcceso":"Deny Access",
    "__________________________________________________":"",
    "Habilitar_Reservas_Titulo":"Enable Reservation",
    "Habilitar_Reservas_Fecha":"Date",
    "Habilitar_Reservas_Hora":"Time",
    "Habilitar_Reservas_Usuario":"User",
    "Habilitar_Reservas_Cantidad_de_Personas":"Number of People",
    "Habilitar_Reservas_Mesa":"Table",
    "Habilitar_Btn_Habilitar":"Enable",
    "Habilitar_Btn_Rechazar":"Reject",
    "Habilitar_option_Cancelar":"Cancel",
    "Habilitar_option_Aceptar":"Accep",
    "______________________dd___________":"_____________",
    "reset_password_titulo ":"Reset Password",
    "reset_password_email ":"Email",
    "reset_password_btn_resetYourPassword ":"Reset Password"


 }];



 public arrayRusia:any=[{
  "HaceTuReserva":"Сделайте заказ!",
  "ElegirFecha":"ВЫБЕРИТЕ ДАТУ БРОНИРОВАНИЯ (ГОД-МЕСЯЦ-ДЕНЬ)",
  "Hora":"Время",
  "Minuto":"Минута",

  "Circulo":"Круг",
  "Barras":"Барс",
  "Porcentajes":"Проценты",

  "graficos":"Графика",
  "TODOS":"ВСЕ ПОЛЯ ОБЯЗАТЕЛЬНЫ К ЗАПОЛНЕНИЮ",
  "Turno":"Перемена",
  "Manana":"полуденный",
  "Mediodia":"полуденный",
  "Noche":"Ночь",
  "Comorecibioelareadetrabajo": "Как вы получили рабочую зону",
  "Impecable":"безупречный",
  "Limpio":"Очищенный",
  "Normal":"Нормальный",
  "sucio":"грязный",
  "asqueroso":"отвратительный",
  "Niveldelimpieza":"Уровень чистоты",
  "CantidaddeFaltasencontradas":"Количество обнаруженных фолов",
  "Comentarios":"Комментарии",

  "aqui_tiene_la_cuenta":"Вот аккаунт ...",
  "Seleccionar":"Выбирать",
  "DescuentoPostre":"Скидка на десерт",
  "Descuento10":"Скидка 10%",
  "DescuentoBebidagratis":"Скидка на бесплатный напиток",
  "Descuento":"скидка",
  "PrecioSinDescuento": "Цена без скидкиo",
  "Mipropina": "Мой совет",
  "TOTAL":"Общее количество",
  "Detalle":"подробность",
  "MostrarTotalConDescuento":"Показать сумму со скидкой",
  

  "alta_pedido_Entregado" :"доставлен",
  "alta_pedido_Seleccione_estado_de_pedido":"Выберите статус заказа",
  "alta_pedido_Tipo_de_pedido":"Тип заказа",
  "alta_pedido_Seleccione_tipo_de_pedido":"Выберите тип заказа:",
  "alta_pedido_pedido":"порядок",
  "alta_pedido_Cuenta":"Билл",
  "alta_pedido_Guardar":"спасти",
  "alta_pedido_Precio_total_Pedido":"Общая стоимость заказа ",
  "Cantidad": "Количество",
  "Producto":"Товар",
  "Monto_Acumulado_Mesa":"Таблица накопленных сумм",
  "Seleccionar":"Выбирать",
  "cargar_pedido":"Загрузить заказ",
  "Editar_pedido":"Редактировать заказ",
  "Estado":"государство",
  "Tipo_de_pedido":"Тип заказа",

  "login_titulo_login":"АВТОРИЗОВАТЬСЯ",
  "login_Textoformulario_email":"ЭЛ. АДРЕС",
  "login_Textoformulario":"MOT DE PASSE",
  "login_PlaceHolder_Ingrese_email":"Введите адрес электронной почты",
  "login_PlaceHolder_Ingrese_clave":"Введите пароль",
  "login_link_CrearUnaNuevaCuenta":"Создать новый аккаунт",
  "login_link_olvidaste_tu_clave": "Забыли Ваш пароль?",
  "login_btn_Ingresar": "Залезай",
  "login_btn_ElegirUsuario": "ВЫБЕРИТЕ ПОЛЬЗОВАТЕЛЯ",
  "login_Mensaje_IngresarMailvalido":"Пожалуйста, введите действительный адрес электронной почты",
  "login_Mensaje_claveMas6Caracteres":"Ваш пароль должен содержать более 6 символов",

  "________________________________":"",
  "tipo_registro_titulo_tiporegistro":"тип регистра",
  "tipo_registro_btn_clienteRegistrado":"Зарегистрированный клиент",
  "tipo_Registro_btn_clienteAnonimo":"Анонимный клиент",
  "_____________________________":"",
  "Alta_Cliente_Titulo":"Загрузить клиент",
  "Alta_Cliente_Formulario_Texto_Nombre":"название",
  "Alta_Cliente_Formulario_Texto_Apellido":"Фамилия",
  "Alta_Cliente_Formulario_Texto_DNI":"DNI",
  "Alta_Cliente_Formulario_Texto_Correo":"почта",
  "Alta_Cliente_Formulario_Texto_Clave":"ключ",
  "Alta_Cliente_Formulario_PlaceHolder_Nombre":"название",
  "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Введите фамилию",
  "Alta_Cliente_Formulario_PlaceHolder_DNI":"Введите DNI",
  "Alta_Cliente_Formulario_PlaceHolder_Correo":"Введите почту",
  "Alta_Cliente_Formulario_PlaceHolder_Clave":"Введите пароль",
  "Alta_Cliente_btn_Scannear_DNI":"сканирование днни",
  "Alta_Cliente_btn_Guardar":"спасти",
  "______________________________":"",
  "alta_duenio_Titulo":"Загрузить владельца / руководителя",
  "alta_duenio_Formulario_Nombre":"название",
  "alta_duenio_Formulario_Apellido":"Фамилия",
  "alta_duenio_Formulario_Cuil":"CUIL",
  "alta_duenio_Formulario_Correo":"почта",
  "alta_duenio_Formulario_TipoDeEmpleado":"Тип сотрудника",
  "alta_duenio_Formulario_Select_OptionSupervisor":"Руководитель",
  "alta_duenio_Formulario_Select_OptionDuenio":"владелец",
  "alta_duenio_Formulario_BTN_ScannerDNI":"сканирование",
  "alta_duenio_Formulario_BTN_Guardar":"спасти",
  "alta_duenio_Listado_Perfil":"Профиль",
  "alta_duenio_Listado_DNI":"DNI",
  "________________Altaempleado_____________________":"",
  "alta_empleado_Titulo":"Добавить сотрудника",
  "alta_empleado_Formulario_Nombre":"название",
  "alta_empleado_Formulario_Apellido":"Фамилия",
  "alta_empleado_Formulario_Cuil":"CUIL",
  "alta_empleado_Formulario_Correo":"почта",
  "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Введите DNI",
  "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Введите CUIL",
  "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Введите почту",
  "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Тип сотрудника",
  "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Выберите тип сотрудников",
  "alta_empleado_Formulario_BTN_ScannerDNI":"Сканирование DNI",
  "alta_empleado_Formulario_BTN_Guardar":"спасти",
  "Alta_empleado_Formulario_Option_Cocinero":"шеф_повар",
  "Alta_empleado_Formulario_Option_Bartender":"буфетчик",
  "Alta_empleado_Formulario_Option_Mozo":"Официант",
  "Alta_empleado_ListadoFormulario_Perfil":"Профиль",
  "Alta_empleado_ListadoFormulario_Empleado":"Наемный рабочий",

  "_______________________________":"",
  "alta_anonimo_titulo":"Загрузить анонимный клиент",
  "alta_anonimo_TextoFormulario_nombre":"название",
  "alta_anonimo_TextoFormularioCorreo":"почта",
  "alta_anonimo_PlaceHolderNombre":"Введите имя",
  "alta_anonimo_PlaceHolderCorreo":"Введите почту",
  "alta_anonimo_PlaceHolderIngreseClave":"Введите пароль",
  "__________________________________":"",
  "alta_mesa_titulo":"Загрузить таблицу",
  "alta_mesa_TextoFormulario_codigo_de_mesa":"Код таблицы",
  "alta_mesa_TextoFormulario_cantidad_de_personas":"Количество людей",
  "alta_mesa_TextoFormulario_tipo_de_mesa":"Тип таблицы",
  "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Выберите тип таблицы",
  "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Выберите количество людей",
  "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Введите код таблицы",
  "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
  "alta_mesa_TextoFormulario_select_Option_Fumadores":"Курильщики",
  "alta_mesa_TextoFormulario_select_Option_Discapacitados":"Отключено",
  "alta_mesa_TextoFormulario_select_Option_Normal":"Нормальный",
  "alta_mesa_btn_Cancelar":"Отмена",
  "alta_mesa_btn_Aceptar":"Принять",
  "alta_mesa_Listado_Estado":"Принять",
  "alta_mesa_Listado_Editar":"редактировать",

  "___________________________________":"",

  "home_btn_CreatuPedido": "СОЗДАЙ СВОЙ ЗАКАЗ",
  "home_btn_ListadoComida":"ПИЩЕВОЙ СПИСОК",
  "home_btn_ReservaCliente":"БРОНИРОВАНИЕ КЛИЕНТА",
  "home_btn_CargarMesa":"ЗАГРУЗИТЬ СТОЛ",
  "home_btn_ConfirmarLLegadaPedido":"ПОДТВЕРЖДАЙТЕ ПРИБЫТИЕ ВАШЕГО ЗАКАЗА",
  "home_btn_EscanearCodigo":"Сканирование вашего кода",
  "home_btn_AltaEmpeado":"Увольнение сотрудника",
  "home_btn_CargarCliente":"ЗАГРУЗИТЬ ЗАКАЗЧИКА",
  "home_btn_ListadoCliente":"СПИСОК КЛИЕНТОВ",
  "home_btn_AbrirMesa": "ОТКРЫТЫЙ СТОЛ",
  "home_btn_cerrarMesa": "ЗАКРЫТЬ СТОЛA",
  "home_btn_TomarPedido":"ПРИНЯТЬ ЗАКАЗ",
  "home_btn_TomarPedidoCocina":"ЗАКАЗАТЬ КУХНЮ",
  "home_btn_ListadoIngreso":"СПИСОК ДОХОДОВ",
  "home_btn_HabilitarReservas":"РАЗРЕШИТЬ БРОНИРОВАНИЕ",
  "home_btn_Hacetudelivery":"ДЕЛАЙ СВОЮ ДОСТАВКУ!",
  "home_btn_Habilitar_Pedido_Delivery":"ВКЛЮЧИТЬ ПОРЯДОК ДОСТАВКИ",
  "home_btn_enviar_Pedido":"ОТПРАВИТЬ ЗАКАЗ ",
  "home_btn_chat":"ЧАТ",
  "home_btn_encuesta_empleado":"ОБСЛУЖИВАНИЕ СОТРУДНИКОВ",
  "home_btn_Cargar_Ciente":"ЗАГРУЗИТЬ ЗАКАЗЧИКА",
  "home_btn_tomar_pedido_bar":"ЗАКАЗАТЬ БАР",
  "home_Bienvenido":"добро пожаловать",
  
  "__________________________":"",
  "comida_list_titulo":"ЗАКАЗАТЬ БАР",
  "comida_list_subtitulo":"ПИЩЕВЫЕ ПИСЬМА",
  "comida_list_bebidas":"НАПИТКИ",
  "comida_list_postre":"ДЕСЕРТНЫЕ ПИСЬМА",

  "comida_list_Precio":"Цена",
  "________________________":"",
  "comida_detail_Titulo":"Описание",
  "comida_detail_Descripcion":"Описание",
  "comida_detail_Precio":"Цена",
  "comida_detail_Tiempo":"Погода",
  "________________":"",
  "comida_create_Titulo":"Загрузить еду",
  "comida_create_FormularioTextNombre":"название",
  "comida_create_FormularioTextCodigo":"Код",
  "comida_create_FormularioTextDescripcion":"Описание",
  "comida_create_FormularioTextPrecio":"Цена",
  "comida_create_FormularioTextPreparacion":"подготовка",
  "comida_create_FormularioTextTipoDeProducto":"Вид продукта",
  "comida_create_PlaceHolder_NombreDeComida":"Название еды",
  "comida_create_PlaceHolder_Codigo":"Код питания",
  "comida_create_PlaceHolder_Descripcion":"Что это?",
  "comida_create_PlaceHolder_CuantoCuesta":"Сколько?",
  "comida_create_PlaceHolder_CuantoTardaenHacerce":"Сколько времени это занимает?",
  "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Выберите тип ",
  "comida_create_Select_PlaceHolder_Comida":"питание",
  "comida_create_Select_PlaceHolder_Bebida":"Пить",
  "comida_create_Select_PlaceHolder_Postre":"Десерт",
  "comida_create_Select_Boton_Cancelar":"Отмена",
  "comida_create_Select_Boton_Aceptar":"Принять",
  "_______________________":"",
  "listado_cliente_Titulo":"Список клиентов",
  "listado_cliente_formulario":"Профиль",
  "_____________________________________":"",
  "abrir_mesa_titulo":"Открытый стол",
  "abrir_mesa_btn_limpiarDatos":"Чистые данные",
  "abrir_mesa_select_option_estado":"штат",
  "abrir_mesa_select_option_cliente":"клиент",
  "abrir_mesa_select_option_ocupado":"занятый",
  "abrir_mesa_select_option_disponible":"доступный",
  "abrir_mesa_select_option_reservada":"зарезервированный",
  "abrir_mesa_btn_cancelar":"Отмена",
  "abrir_mesa_btn_aceptar":"принять",
  "abrir_mesa_mesa":"стол",

  "___________________________________________":"",
  "tomarpedidos_titulo":"Загрузить заказ",
  "tomarpedidos_listosParaEntregar":"Готовы доставить",
  "tomarpedidos_pendientes_de_aprobacion":"Заказы, ожидающие утверждения",
  "_____________________________________________":"",
  "ingreso_Titulo ":"Лист ожидания",
  "ingreso_cliente_en_espera":"ожидание клиента",
  "ingreso_estado":"штат",
  "ingreso_btn_confirmarIngreso":"Подтвердите логин",
  "ingreso_btn_DenegarAcceso":"Запретить доступ",
  "__________________________________________________":"",
  "Habilitar_Reservas_Titulo":"Включить бронирование",
  "Habilitar_Reservas_Fecha":"Дата",
  "Habilitar_Reservas_Hora":"Час",
  "Habilitar_Reservas_Usuario":"пользователь",
  "Habilitar_Reservas_Cantidad_de_Personas":"Количество людей",
  "Habilitar_Reservas_Mesa":"Стол",
  "Habilitar_Btn_Habilitar":"включить",
  "Habilitar_Btn_Rechazar":"Отказаться",
  "Habilitar_option_Cancelar":"Отмена",
  "Habilitar_option_Aceptar":"Принять",
  ":::::::::::::":"",
  "reset_password_titulo ":"Сброс пароля",
  "reset_password_email ":"Эл. адрес",
  "reset_password_btn_resetYourPassword ":"Сброс пароля"




}];


public arrayPor: any =[
{
  "HaceTuReserva":"Faça sua reserva!",
"ElegirFecha":"ESCOLHER A DATA DA RESERVA (ANO-MÊS-DIA)",
"Hora":"Hora",
"Minuto":"Minuto",

  "Circulo":"Circulo",
  "Barras":"Barras",
  "Porcentajes":"Porcentagens",
  "graficos":"Graficos",
  "TODOS":"TODOS OS CAMPOS SÃO OBRIGATÓRIOS",
  "Turno":"Virar",
  "Manana":"Manhã",
  "Mediodia":"Meio-dia",
  "Noche":"Noite",
  "Comorecibioelareadetrabajo": "Como você recebeu a área de trabalho",
  "Impecable":"Impecável",
  "Limpio":"Limpo",
  "Normal":"Normal",
  "sucio":"sujo",
  "asqueroso":"repugnante",
  "Niveldelimpieza":"Nível de limpeza",
  "CantidaddeFaltasencontradas":"Quantidade de faltas encontradas",
  "Comentarios":"Comentários",

  "aqui_tiene_la_cuenta":"Aqui está a conta ...",
  "Seleccionar":"Selecionar",
  "DescuentoPostre":"Desconto de sobremesa",
  "Descuento10":"Desconto 10%",
  "DescuentoBebidagratis":"Bebida grátis com desconto",
  "Descuento":"Desconto",
  "PrecioSinDescuento": "Preço sem desconto",
  "Mipropina": "Minha dica",
  "TOTAL":"Total",
  "Detalle":"Detalhe",
  "MostrarTotalConDescuento":"Mostrar total com desconto ",

  "alta_pedido_Entregado" :"Entregue",
  "alta_pedido_Seleccione_estado_de_pedido":"Selecionar status do pedido",
  "alta_pedido_Tipo_de_pedido":"Tipo de pedido",
  "alta_pedido_Seleccione_tipo_de_pedido":"Selecione o tipo de pedido:",
  "alta_pedido_pedido":"Pedido",
  "alta_pedido_Cuenta":"Conta",
  "alta_pedido_Guardar":"Salve ",
  "alta_pedido_Precio_total_Pedido":"Pedido de preço total",
  "Cantidad": "Quantidade",
  "Producto":"Produtos",
  "Monto_Acumulado_Mesa":"Tabela de Montantes Acumulados",
  "Seleccionar":"Selecionar",
  "cargar_pedido":"Carregar pedido",
  "Editar_pedido":"Editar pedido",
  "Estado":"Status",
  "Tipo_de_pedido":"Tipo de pedido",

  "login_titulo_login":"INICIAR SESSÃO",
  "login_Textoformulario_email":"CORREIO ELETRÔNICO",
  "login_Textoformulario":"CHAVE",
  "login_PlaceHolder_Ingrese_email":"Introduzir email",
  "login_PlaceHolder_Ingrese_clave":"Digite a senha",
  "login_link_CrearUnaNuevaCuenta":"Criar uma nova conta",
  "login_link_olvidaste_tu_clave": "Esqueceu sua senha?",
  "login_btn_Ingresar": "ENTRAR",
  "login_btn_ElegirUsuario": "ESCOLHA O USUÁRIO",
  "login_Mensaje_IngresarMailvalido":"Por favor digite um email válido",
  "login_Mensaje_claveMas6Caracteres":"Sua senha deve ter mais de 6 caracteres",

  "________________________________":"",
  "tipo_registro_titulo_tiporegistro":"Tipo Registro",
  "tipo_registro_btn_clienteRegistrado":"Cliente Registrado",
  "tipo_Registro_btn_clienteAnonimo":"Cliente anônimo",
  "_____________________________":"",
  "Alta_Cliente_Titulo":"Carregar cliente",
  "Alta_Cliente_Formulario_Texto_Nombre":"Nome",
  "Alta_Cliente_Formulario_Texto_Apellido":"Sobrenome",
  "Alta_Cliente_Formulario_Texto_DNI":"DNI",
  "Alta_Cliente_Formulario_Texto_Correo":"o email",
  "Alta_Cliente_Formulario_Texto_Clave":"senha",
  "Alta_Cliente_Formulario_PlaceHolder_Nombre":"Nome",
  "Alta_Cliente_Formulario_PlaceHolder_Apellido":"Insira o último nome",
  "Alta_Cliente_Formulario_PlaceHolder_DNI":"Digite DNI",
  "Alta_Cliente_Formulario_PlaceHolder_Correo":"Inserir email",
  "Alta_Cliente_Formulario_PlaceHolder_Clave":"Digite a senha",
  "Alta_Cliente_btn_Scannear_DNI":"Varredura DNI",
  "Alta_Cliente_btn_Guardar":"Salve",
  "______________________________":"",
  "alta_duenio_Titulo":"Carregar proprietário / supervisor",
  "alta_duenio_Formulario_Nombre":"Nome",
  "alta_duenio_Formulario_Apellido":"Sorenome",
  "alta_duenio_Formulario_Cuil":"CUIL",
  "alta_duenio_Formulario_Correo":"o email",
  "alta_duenio_Formulario_TipoDeEmpleado":"Tipo de funcionário",
  "alta_duenio_Formulario_Select_OptionSupervisor":"Supervisor",
  "alta_duenio_Formulario_Select_OptionDuenio":"Proprietário",
  "alta_duenio_Formulario_BTN_ScannerDNI":"Varredura",
  "alta_duenio_Formulario_BTN_Guardar":"Salve",
  "alta_duenio_Listado_Perfil":"Perfil",
  "alta_duenio_Listado_DNI":"DNI",
  "________________Altaempleado_____________________":"",
  "alta_empleado_Titulo":"Adicionar funcionário",
  "alta_empleado_Formulario_Nombre":"Nome",
  "alta_empleado_Formulario_Apellido":"Sobrenome",
  "alta_empleado_Formulario_Cuil":"CUIL",
  "alta_empleado_Formulario_Correo":"O email",
  "Alta_empleado_Formulario_PlaceHolder_IngreseDni":"Digite DNI",
  "Alta_empleado_Formulario_PlaceHolder_IngreseCuil":"Digite CUIL",
  "Alta_empleado_Formulario_PlaceHolder_IngresarCorreo":"Digite O email",
  "Alta_empleado_Formulario_PlaceHolder_TipoEmpleado":"Tipo de funcionário",
  "Alta_empleado_Formulario_PlaceHolder_SeleccioneTipoEmpleado":"Selecione o tipo de funcionários",
  "alta_empleado_Formulario_BTN_ScannerDNI":"digitalizar dni",
  "alta_empleado_Formulario_BTN_Guardar":"Salve ",
  "Alta_empleado_Formulario_Option_Cocinero":"Chefe de cozinha",
  "Alta_empleado_Formulario_Option_Bartender":"Barman",
  "Alta_empleado_Formulario_Option_Mozo":"Garçom",
  "Alta_empleado_ListadoFormulario_Perfil":"Perfil",
  "Alta_empleado_ListadoFormulario_Empleado":"Empregado",

  "_______________________________":"",
  "alta_anonimo_titulo":"Carregar cliente anônimo",
  "alta_anonimo_TextoFormulario_nombre":"Nome",
  "alta_anonimo_TextoFormularioCorreo":"Enviar",
  "alta_anonimo_PlaceHolderNombre":"Insira o nome",
  "alta_anonimo_PlaceHolderCorreo":"Inserir email",
  "alta_anonimo_PlaceHolderIngreseClave":"Digite a senha",
  "__________________________________":"",
  "alta_mesa_titulo":"Carregar mêsa",
  "alta_mesa_TextoFormulario_codigo_de_mesa":"Código da tabela",
  "alta_mesa_TextoFormulario_cantidad_de_personas":"Quantidade de pessoas",
  "alta_mesa_TextoFormulario_tipo_de_mesa":"Tipo de tabela",
  "alta_mesa_TextoFormulario_PlaceholderseleccionartipoDemesa":"Selecionar tipo de tabela",
  "alta_mesa_TextoFormulario_PlaceholderseleccionarCantidadDePersonas":"Selecione o número de pessoas",
  "alta_mesa_TextoFormulario_PlaceholderCodigoDeMesa":"Digite o código da tabela",
  "alta_mesa_TextoFormulario_select_Option_VIP":"VIP",
  "alta_mesa_TextoFormulario_select_Option_Fumadores":"Fumantes",
  "alta_mesa_TextoFormulario_select_Option_Discapacitados":"Desativado",
  "alta_mesa_TextoFormulario_select_Option_Normal":"Normal",
  "alta_mesa_btn_Cancelar":"Cancelar",
  "alta_mesa_btn_Aceptar":"Aceitar",
  "alta_mesa_Listado_Estado":"Estado",
  "alta_mesa_Listado_Editar":"Editar",



  "___________________________________":"",

  "home_btn_CreatuPedido": "CRIE SUA ORDEM",
  "home_btn_ListadoComida":"LISTA DE ALIMENTOS",
  "home_btn_ReservaCliente":"RESERVA DE CLIENTE ",
  "home_btn_CargarMesa":"TABELA DE CARGA",
  "home_btn_ConfirmarLLegadaPedido":"CONFIRME A CHEGADA DE SUA ORDEM",
  "home_btn_EscanearCodigo":"VERIFIQUE SEU CÓDIGO",
  "home_btn_AltaEmpeado":"DESCARGA DE FUNCIONÁRIO",
  "home_btn_CargarCliente":"CARREGAR CLIENTE ",
  "home_btn_ListadoCliente":"LISTA DE CLIENTES",
  "home_btn_AbrirMesa": "MESA ABERTA",
  "home_btn_cerrarMesa": "FECHADO ABERTO",
  "home_btn_TomarPedido":"ANOTAR UM PEDIDO",
  "home_btn_TomarPedidoCocina":"COZINHA DE PEDIDO",
  "home_btn_ListadoIngreso":"LISTA DE RENDA",
  "home_btn_HabilitarReservas":"ATIVAR RESERVAS",
  "home_btn_Hacetudelivery":"FAÇA SUA ENTREGA!",
  "home_btn_Habilitar_Pedido_Delivery":"ATIVAR PEDIDO DE ENTREGA",
  "home_btn_enviar_Pedido":"ENVIAR A ORDEM",
  "home_btn_chat":"BATE_PAPO",
  "home_btn_encuesta_empleado":"PESQUISA DE EMPREGADOS",
  "home_btn_Cargar_Ciente":"CARREGAR CLIENTE",
  "home_btn_tomar_pedido_bar":"TAKE ORDERS BAR",
  "home_Bienvenido":"bem-vinda",

  "__________________________":"",
  "comida_list_titulo":"TOMAR PEDIDOS BAR",
  "comida_list_subtitulo":"CARTAS ALIMENTARES",
  "comida_list_bebidas":"LETRAS DE BEBIDAS",
  "comida_list_postre":"CARTAS DE SOBREMESA",

  "comida_list_Precio":"Preço",
  "________________________":"",
  "comida_detail_Titulo":"Descrição",
  "comida_detail_Descripcion":"Descrição",
  "comida_detail_Precio":"Preço",
  "comida_detail_Tiempo":"Clima",
  "________________":"",
  "comida_create_Titulo":"Carregar Comida",
  "comida_create_FormularioTextNombre":"Nome",
  "comida_create_FormularioTextCodigo":"Código",
  "comida_create_FormularioTextDescripcion":"Descrição",
  "comida_crePreçoate_FormularioTextPrecio":"Preço",
  "comida_create_FormularioTextPreparacion":"Preparação",
  "comida_create_FormularioTextTipoDeProducto":"Tipo de produto",
  "comida_create_PlaceHolder_NombreDeComida":"Nome do alimento",
  "comida_create_PlaceHolder_Codigo":"Código alimentar",
  "comida_create_PlaceHolder_Descripcion":"O que é?",
  "comida_create_PlaceHolder_CuantoCuesta":"Quanto custa?",
  "comida_create_PlaceHolder_CuantoTardaenHacerce":"Quanto tempo leva?",
  "comida_create_Select_PlaceHolder_SeleccioneElTipo":"Selecione o tipo",
  "comida_create_Select_PlaceHolder_Comida":"Comida",
  "comida_create_Select_PlaceHolder_Bebida":"Bebida",
  "comida_create_Select_PlaceHolder_Postre":"Sobremesa",
  "comida_create_Select_Boton_Cancelar":"Cancelar",
  "comida_create_Select_Boton_Aceptar":"Aceitar",
  "_______________________":"",
  "listado_cliente_Titulo":"Lista de clientes",
  "listado_cliente_formulario":"Perfil",
  "_____________________________________":"",
  "abrir_mesa_titulo":"Mesa aberta",
  "abrir_mesa_btn_limpiarDatos":"Dados limpos",
  "abrir_mesa_select_option_estado":"Estado",
  "abrir_mesa_select_option_cliente":"cliente",
  "abrir_mesa_select_option_ocupado":"ocupado",
  "abrir_mesa_select_option_disponible":"acessível",
  "abrir_mesa_select_option_reservada":"reservado",
  "abrir_mesa_btn_cancelar":"cancelar",
  "abrir_mesa_btn_aceptar":"aceitar",
  "abrir_mesa_mesa":"tabela",
  "___________________________________________":"",
  "tomarpedidos_titulo":"Carregar pedido",
  "tomarpedidos_listosParaEntregar":"Pronto para entregar",
  "tomarpedidos_pendientes_de_aprobacion":"Pedidos com aprovação pendente",
  "_____________________________________________":"",
  "ingreso_Titulo ":"Lista de Espera",
  "ingreso_cliente_en_espera":"cliente em espera",
  "ingreso_estado":"estado",
  "ingreso_btn_confirmarIngreso":"Confirmar login",
  "ingreso_btn_DenegarAcceso":"Negar acesso",
  "__________________________________________________":"",
  "Habilitar_Reservas_Titulo":"Ativar reservas",
  "Habilitar_Reservas_Fecha":"Encontro",
  "Habilitar_Reservas_Hora":"Hora",
  "Habilitar_Reservas_Usuario":"Do utilizador",
  "Habilitar_Reservas_Cantidad_de_Personas":"Quantidade de Pessoas",
  "Habilitar_Reservas_Mesa":"Tabela",
  "Habilitar_Btn_Habilitar":"Habilitar",
  "Habilitar_Btn_Rechazar":"Recusar",
  "Habilitar_option_Cancelar":"Cancelar",
  "Habilitar_option_Aceptar":"Aceitar",
  "::::::::::::::::::::::________________::::::":"",
  "reset_password_titulo ":"Redefinir senha",
  "reset_password_email ":"o email",
  "reset_password_btn_resetYourPassword ":"Redefinir senha"





}];


}
